springs.persistenceorm.users.people[0].username=admin1
springs.persistenceorm.users.people[0].password=admin1password
springs.persistenceorm.users.people[0].name.salutation=MR
springs.persistenceorm.users.people[0].name.first=First Admin1
springs.persistenceorm.users.people[0].name.middle=Middle Admin1
springs.persistenceorm.users.people[0].name.last=Last Admin1
springs.persistenceorm.users.people[0].name.suffix=IV
springs.persistenceorm.users.people[0].dateOfBirth=1980-01-01
springs.persistenceorm.users.people[0].status=ACT
springs.persistenceorm.users.people[0].languages[0].i18n=EN
springs.persistenceorm.users.people[0].languages[0].l10n=US
springs.persistenceorm.users.people[0].languages[0].canSpeak=true
springs.persistenceorm.users.people[0].languages[0].canListen=true
springs.persistenceorm.users.people[0].languages[0].canRead=true
springs.persistenceorm.users.people[0].languages[0].canWrite=true
springs.persistenceorm.users.people[0].timezones[0]=America/New_York
springs.persistenceorm.users.people[0].personas[0].personaType=ADM
springs.persistenceorm.users.people[0].personas[0].emailAddresses[0].emailAddress=admin1@example.com
springs.persistenceorm.users.people[0].personas[0].emailAddresses[0].type=WRK
springs.persistenceorm.users.people[0].personas[0].phoneNumbers[0].phoneNumber=+12345678901
springs.persistenceorm.users.people[0].personas[0].phoneNumbers[0].canTalk=true
springs.persistenceorm.users.people[0].personas[0].phoneNumbers[0].canText=true
springs.persistenceorm.users.people[0].personas[0].phoneNumbers[0].hasData=true
springs.persistenceorm.users.people[0].personas[0].phoneNumbers[0].type=MOBILE
springs.persistenceorm.users.people[0].personas[0].locationAddresses[0].street1=123 Admin St
springs.persistenceorm.users.people[0].personas[0].locationAddresses[0].street2=Suite 500
springs.persistenceorm.users.people[0].personas[0].locationAddresses[0].city=Admin City
springs.persistenceorm.users.people[0].personas[0].locationAddresses[0].state=Admin State
springs.persistenceorm.users.people[0].personas[0].locationAddresses[0].country=Admin Country
springs.persistenceorm.users.people[0].personas[0].locationAddresses[0].type=WRK
springs.persistenceorm.users.people[0].personas[0].urls[0].url=https://admin1.com
springs.persistenceorm.users.people[0].personas[0].urls[0].type=WORK_PROFILE

springs.persistenceorm.users.people[1].username=operator1
springs.persistenceorm.users.people[1].password=operator1password
springs.persistenceorm.users.people[1].name.salutation=MR
springs.persistenceorm.users.people[1].name.first=First Operator1
springs.persistenceorm.users.people[1].name.middle=Middle Operator1
springs.persistenceorm.users.people[1].name.last=Last Operator1
springs.persistenceorm.users.people[1].name.suffix=VIII
springs.persistenceorm.users.people[1].dateOfBirth=1985-05-05
springs.persistenceorm.users.people[1].status=ACT
springs.persistenceorm.users.people[1].languages[0].i18n=ZH
springs.persistenceorm.users.people[1].languages[0].l10n=CN
springs.persistenceorm.users.people[1].languages[0].canSpeak=true
springs.persistenceorm.users.people[1].languages[0].canListen=true
springs.persistenceorm.users.people[1].languages[0].canRead=true
springs.persistenceorm.users.people[1].languages[0].canWrite=true
springs.persistenceorm.users.people[1].timezones[0]=Europe/London
springs.persistenceorm.users.people[1].personas[0].personaType=OPR
springs.persistenceorm.users.people[1].personas[0].emailAddresses[0].emailAddress=operator1@example.com
springs.persistenceorm.users.people[1].personas[0].emailAddresses[0].type=WRK
springs.persistenceorm.users.people[1].personas[0].phoneNumbers[0].phoneNumber=+12345678902
springs.persistenceorm.users.people[1].personas[0].phoneNumbers[0].canTalk=true
springs.persistenceorm.users.people[1].personas[0].phoneNumbers[0].canText=true
springs.persistenceorm.users.people[1].personas[0].phoneNumbers[0].hasData=true
springs.persistenceorm.users.people[1].personas[0].phoneNumbers[0].type=MOBILE
springs.persistenceorm.users.people[1].personas[0].locationAddresses[0].street1=456 Operator Ave
springs.persistenceorm.users.people[1].personas[0].locationAddresses[0].street2=Suite 500
springs.persistenceorm.users.people[1].personas[0].locationAddresses[0].city=Operator City
springs.persistenceorm.users.people[1].personas[0].locationAddresses[0].state=Operator State
springs.persistenceorm.users.people[1].personas[0].locationAddresses[0].country=Operator Country
springs.persistenceorm.users.people[1].personas[0].locationAddresses[0].type=WRK
springs.persistenceorm.users.people[1].personas[0].urls[0].url=https://operator1.com
springs.persistenceorm.users.people[1].personas[0].urls[0].type=WORK_PROFILE

springs.persistenceorm.users.people[2].username=user1
springs.persistenceorm.users.people[2].password=user1password
springs.persistenceorm.users.people[2].dateOfBirth=2000-06-06
springs.persistenceorm.users.people[2].name.salutation=MR
springs.persistenceorm.users.people[2].name.first=First User1
springs.persistenceorm.users.people[2].name.middle=Middle User1
springs.persistenceorm.users.people[2].name.last=Last User1
springs.persistenceorm.users.people[2].name.suffix=X
springs.persistenceorm.users.people[2].status=ACT
springs.persistenceorm.users.people[2].languages[0].i18n=ES
springs.persistenceorm.users.people[2].languages[0].l10n=MX
springs.persistenceorm.users.people[2].languages[0].canSpeak=true
springs.persistenceorm.users.people[2].languages[0].canListen=true
springs.persistenceorm.users.people[2].languages[0].canRead=true
springs.persistenceorm.users.people[2].languages[0].canWrite=true
springs.persistenceorm.users.people[2].timezones[0]=Europe/Paris
springs.persistenceorm.users.people[2].personas[0].personaType=REG
springs.persistenceorm.users.people[2].personas[0].emailAddresses[0].emailAddress=user1@example.com
springs.persistenceorm.users.people[2].personas[0].emailAddresses[0].type=PER
springs.persistenceorm.users.people[2].personas[0].phoneNumbers[0].phoneNumber=+12345678905
springs.persistenceorm.users.people[2].personas[0].phoneNumbers[0].canTalk=true
springs.persistenceorm.users.people[2].personas[0].phoneNumbers[0].canText=true
springs.persistenceorm.users.people[2].personas[0].phoneNumbers[0].hasData=true
springs.persistenceorm.users.people[2].personas[0].phoneNumbers[0].type=MOBILE
springs.persistenceorm.users.people[2].personas[0].locationAddresses[0].street1=102 User Lane
springs.persistenceorm.users.people[2].personas[0].locationAddresses[0].street2=Suite 500
springs.persistenceorm.users.people[2].personas[0].locationAddresses[0].city=User City
springs.persistenceorm.users.people[2].personas[0].locationAddresses[0].state=User State
springs.persistenceorm.users.people[2].personas[0].locationAddresses[0].country=User Country
springs.persistenceorm.users.people[2].personas[0].locationAddresses[0].type=HME
springs.persistenceorm.users.people[2].personas[0].urls[0].url=https://user1.com
springs.persistenceorm.users.people[2].personas[0].urls[0].type=WORK_PROFILE
