springs.authenticationorm.users[0].username=admin1
springs.authenticationorm.users[0].password=admin1password
springs.authenticationorm.users[0].name.salutation=MR
springs.authenticationorm.users[0].name.first=First Admin1
springs.authenticationorm.users[0].name.middle=Middle Admin1
springs.authenticationorm.users[0].name.last=Last Admin1
springs.authenticationorm.users[0].name.suffix=IV
springs.authenticationorm.users[0].dateOfBirth=1980-01-01
springs.authenticationorm.users[0].status=ACT
springs.authenticationorm.users[0].languages[0].i18n=EN
springs.authenticationorm.users[0].languages[0].l10n=US
springs.authenticationorm.users[0].languages[0].canSpeak=true
springs.authenticationorm.users[0].languages[0].canListen=true
springs.authenticationorm.users[0].languages[0].canRead=true
springs.authenticationorm.users[0].languages[0].canWrite=true
springs.authenticationorm.users[0].timezones[0]=America/New_York
springs.authenticationorm.users[0].personas[0].personaType=ADM
springs.authenticationorm.users[0].personas[0].emailAddresses[0].emailAddress=admin1@example.com
springs.authenticationorm.users[0].personas[0].emailAddresses[0].type=WRK
springs.authenticationorm.users[0].personas[0].phoneNumbers[0].phoneNumber=+12345678901
springs.authenticationorm.users[0].personas[0].phoneNumbers[0].canTalk=true
springs.authenticationorm.users[0].personas[0].phoneNumbers[0].canText=true
springs.authenticationorm.users[0].personas[0].phoneNumbers[0].hasData=true
springs.authenticationorm.users[0].personas[0].phoneNumbers[0].type=MOBILE
springs.authenticationorm.users[0].personas[0].locationAddresses[0].locationAddress=123 Admin St, Admin City, Admin Country
springs.authenticationorm.users[0].personas[0].locationAddresses[0].type=WRK
springs.authenticationorm.users[0].personas[0].urls[0].url=https://admin1.com
springs.authenticationorm.users[0].personas[0].urls[0].type=WORK_PROFILE

springs.authenticationorm.users[1].username=operator1
springs.authenticationorm.users[1].password=operator1password
springs.authenticationorm.users[1].name.salutation=MR
springs.authenticationorm.users[1].name.first=First Operator1
springs.authenticationorm.users[1].name.middle=Middle Operator1
springs.authenticationorm.users[1].name.last=Last Operator1
springs.authenticationorm.users[1].name.suffix=VIII
springs.authenticationorm.users[1].dateOfBirth=1985-05-05
springs.authenticationorm.users[1].status=ACT
springs.authenticationorm.users[1].languages[0].i18n=ZH
springs.authenticationorm.users[1].languages[0].l10n=CN
springs.authenticationorm.users[1].languages[0].canSpeak=true
springs.authenticationorm.users[1].languages[0].canListen=true
springs.authenticationorm.users[1].languages[0].canRead=true
springs.authenticationorm.users[1].languages[0].canWrite=true
springs.authenticationorm.users[1].timezones[0]=Europe/London
springs.authenticationorm.users[1].personas[0].personaType=OPR
springs.authenticationorm.users[1].personas[0].emailAddresses[0].emailAddress=operator1@example.com
springs.authenticationorm.users[1].personas[0].emailAddresses[0].type=WRK
springs.authenticationorm.users[1].personas[0].phoneNumbers[0].phoneNumber=+12345678902
springs.authenticationorm.users[1].personas[0].phoneNumbers[0].canTalk=true
springs.authenticationorm.users[1].personas[0].phoneNumbers[0].canText=true
springs.authenticationorm.users[1].personas[0].phoneNumbers[0].hasData=true
springs.authenticationorm.users[1].personas[0].phoneNumbers[0].type=MOBILE
springs.authenticationorm.users[1].personas[0].locationAddresses[0].locationAddress=456 Operator Ave, Operator City, Operator Country
springs.authenticationorm.users[1].personas[0].locationAddresses[0].type=WRK
springs.authenticationorm.users[1].personas[0].urls[0].url=https://operator1.com
springs.authenticationorm.users[1].personas[0].urls[0].type=WORK_PROFILE

springs.authenticationorm.users[2].username=user1
springs.authenticationorm.users[2].password=user1password
springs.authenticationorm.users[2].dateOfBirth=2000-06-06
springs.authenticationorm.users[2].name.salutation=MR
springs.authenticationorm.users[2].name.first=First User1
springs.authenticationorm.users[2].name.middle=Middle User1
springs.authenticationorm.users[2].name.last=Last User1
springs.authenticationorm.users[2].name.suffix=X
springs.authenticationorm.users[2].status=ACT
springs.authenticationorm.users[2].languages[0].i18n=ES
springs.authenticationorm.users[2].languages[0].l10n=MX
springs.authenticationorm.users[2].languages[0].canSpeak=true
springs.authenticationorm.users[2].languages[0].canListen=true
springs.authenticationorm.users[2].languages[0].canRead=true
springs.authenticationorm.users[2].languages[0].canWrite=true
springs.authenticationorm.users[2].timezones[0]=Europe/Paris
springs.authenticationorm.users[2].personas[0].personaType=REG
springs.authenticationorm.users[2].personas[0].emailAddresses[0].emailAddress=user1@example.com
springs.authenticationorm.users[2].personas[0].emailAddresses[0].type=PER
springs.authenticationorm.users[2].personas[0].phoneNumbers[0].phoneNumber=+12345678905
springs.authenticationorm.users[2].personas[0].phoneNumbers[0].canTalk=true
springs.authenticationorm.users[2].personas[0].phoneNumbers[0].canText=true
springs.authenticationorm.users[2].personas[0].phoneNumbers[0].hasData=true
springs.authenticationorm.users[2].personas[0].phoneNumbers[0].type=MOBILE
springs.authenticationorm.users[2].personas[0].locationAddresses[0].locationAddress=102 User Lane, User City, User Country
springs.authenticationorm.users[2].personas[0].locationAddresses[0].type=HME
springs.authenticationorm.users[2].personas[0].urls[0].url=https://user1.com
springs.authenticationorm.users[2].personas[0].urls[0].type=WORK_PROFILE
