springs.authenticationorm.users.admin1.username=admin1
springs.authenticationorm.users.admin1.password=admin1password
springs.authenticationorm.users.admin1.name.salutation=MR
springs.authenticationorm.users.admin1.name.first=First Admin1
springs.authenticationorm.users.admin1.name.middle=Middle Admin1
springs.authenticationorm.users.admin1.name.last=Last Admin1
springs.authenticationorm.users.admin1.name.suffix=IV
springs.authenticationorm.users.admin1.dateOfBirth=1980-01-01
springs.authenticationorm.users.admin1.status=ACT
springs.authenticationorm.users.admin1.languages[0].i18n=EN
springs.authenticationorm.users.admin1.languages[0].l10n=US
springs.authenticationorm.users.admin1.languages[0].canSpeak=true
springs.authenticationorm.users.admin1.languages[0].canListen=true
springs.authenticationorm.users.admin1.languages[0].canRead=true
springs.authenticationorm.users.admin1.languages[0].canWrite=true
springs.authenticationorm.users.admin1.timezones[0]=America/New_York
springs.authenticationorm.users.admin1.personas[0].personaType=ADM
springs.authenticationorm.users.admin1.personas[0].emailAddresses[0].emailAddress=admin1@example.com
springs.authenticationorm.users.admin1.personas[0].emailAddresses[0].type=WRK
springs.authenticationorm.users.admin1.personas[0].phoneNumbers[0].phoneNumber=+12345678901
springs.authenticationorm.users.admin1.personas[0].phoneNumbers[0].type=MOBILE
springs.authenticationorm.users.admin1.personas[0].locationAddresses[0].locationAddress=123 Admin St, Admin City, Admin Country
springs.authenticationorm.users.admin1.personas[0].locationAddresses[0].type=WRK
springs.authenticationorm.users.admin1.personas[0].urls[0].url=https://admin1.com
springs.authenticationorm.users.admin1.personas[0].urls[0].type=WORK_PROFILE

springs.authenticationorm.users.operator1.username=operator1
springs.authenticationorm.users.operator1.password=operator1password
springs.authenticationorm.users.operator1.name.salutation=MR
springs.authenticationorm.users.operator1.name.first=First Operator1
springs.authenticationorm.users.operator1.name.middle=Middle Operator1
springs.authenticationorm.users.operator1.name.last=Last Operator1
springs.authenticationorm.users.operator1.name.suffix=VIII
springs.authenticationorm.users.operator1.dateOfBirth=1985-05-05
springs.authenticationorm.users.operator1.status=ACT
springs.authenticationorm.users.operator1.languages[0].i18n=ZH
springs.authenticationorm.users.operator1.languages[0].l10n=CN
springs.authenticationorm.users.operator1.languages[0].canSpeak=true
springs.authenticationorm.users.operator1.languages[0].canListen=true
springs.authenticationorm.users.operator1.languages[0].canRead=true
springs.authenticationorm.users.operator1.languages[0].canWrite=true
springs.authenticationorm.users.operator1.timezones[0]=Europe/London
springs.authenticationorm.users.operator1.personas[0].personaType=OPR
springs.authenticationorm.users.operator1.personas[0].emailAddresses[0].emailAddress=operator1@example.com
springs.authenticationorm.users.operator1.personas[0].emailAddresses[0].type=WRK
springs.authenticationorm.users.operator1.personas[0].phoneNumbers[0].phoneNumber=+12345678902
springs.authenticationorm.users.operator1.personas[0].phoneNumbers[0].type=MOBILE
springs.authenticationorm.users.operator1.personas[0].locationAddresses[0].locationAddress=456 Operator Ave, Operator City, Operator Country
springs.authenticationorm.users.operator1.personas[0].locationAddresses[0].type=WRK
springs.authenticationorm.users.operator1.personas[0].urls[0].url=https://operator1.com
springs.authenticationorm.users.operator1.personas[0].urls[0].type=WORK_PROFILE

springs.authenticationorm.users.user1.username=user1
springs.authenticationorm.users.user1.password=user1password
springs.authenticationorm.users.user1.dateOfBirth=2000-06-06
springs.authenticationorm.users.user1.name.salutation=MR
springs.authenticationorm.users.user1.name.first=First User1
springs.authenticationorm.users.user1.name.middle=Middle User1
springs.authenticationorm.users.user1.name.last=Last User1
springs.authenticationorm.users.user1.name.suffix=X
springs.authenticationorm.users.user1.status=ACT
springs.authenticationorm.users.user1.languages[0].i18n=ES
springs.authenticationorm.users.user1.languages[0].l10n=MX
springs.authenticationorm.users.user1.languages[0].canSpeak=true
springs.authenticationorm.users.user1.languages[0].canListen=true
springs.authenticationorm.users.user1.languages[0].canRead=true
springs.authenticationorm.users.user1.languages[0].canWrite=true
springs.authenticationorm.users.user1.timezones[0]=Europe/Paris
springs.authenticationorm.users.user1.personas[0].personaType=REG
springs.authenticationorm.users.user1.personas[0].emailAddresses[0].emailAddress=user1@example.com
springs.authenticationorm.users.user1.personas[0].emailAddresses[0].type=PER
springs.authenticationorm.users.user1.personas[0].phoneNumbers[0].phoneNumber=+12345678905
springs.authenticationorm.users.user1.personas[0].phoneNumbers[0].type=MOBILE
springs.authenticationorm.users.user1.personas[0].locationAddresses[0].locationAddress=102 User Lane, User City, User Country
springs.authenticationorm.users.user1.personas[0].locationAddresses[0].type=HME
springs.authenticationorm.users.user1.personas[0].urls[0].url=https://user1.com
springs.authenticationorm.users.user1.personas[0].urls[0].type=WORK_PROFILE
