springs.util.security.passwords.users.minLength=12
springs.util.security.passwords.users.maxLength=128
springs.util.security.passwords.users.maxAnywhereRepeats=3
springs.util.security.passwords.users.maxConsecutiveRepeats=2
springs.util.security.passwords.users.firsts=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
springs.util.security.passwords.users.lasts=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

springs.util.security.passwords.users.uppers=ABCDEFGHIJKLMNOPQRSTUVWXYZ
springs.util.security.passwords.users.lowers=abcdefghijklmnopqrstuvwxyz
springs.util.security.passwords.users.digits=0123456789
springs.util.security.passwords.users.specials=~`!@#$%^&*()_-+={}[]|\\\"':;?/<>,.
springs.util.security.passwords.users.whitespace=
springs.util.security.passwords.users.minUppers=1
springs.util.security.passwords.users.maxUppers=128
springs.util.security.passwords.users.minLowers=1
springs.util.security.passwords.users.maxLowers=128
springs.util.security.passwords.users.minDigits=1
springs.util.security.passwords.users.maxDigits=128
springs.util.security.passwords.users.minSpecials=1
springs.util.security.passwords.users.maxSpecials=128
springs.util.security.passwords.users.minWhitespace=0
springs.util.security.passwords.users.maxWhitespace=128

springs.util.security.passwords.clients.minLength=43
springs.util.security.passwords.clients.maxLength=128
springs.util.security.passwords.clients.maxAnywhereRepeats=2
springs.util.security.passwords.clients.maxConsecutiveRepeats=2
springs.util.security.passwords.clients.firsts=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
springs.util.security.passwords.clients.lasts=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

springs.util.security.passwords.clients.uppers=ABCDEFGHIJKLMNOPQRSTUVWXYZ
springs.util.security.passwords.clients.lowers=abcdefghijklmnopqrstuvwxyz
springs.util.security.passwords.clients.digits=0123456789
springs.util.security.passwords.clients.specials=~`!@#$%^&*()_-+={}[]|\\\"':;?/<>,.
springs.util.security.passwords.clients.whitespace=
springs.util.security.passwords.clients.minUppers=1
springs.util.security.passwords.clients.maxUppers=128
springs.util.security.passwords.clients.minLowers=1
springs.util.security.passwords.clients.maxLowers=128
springs.util.security.passwords.clients.minDigits=1
springs.util.security.passwords.clients.maxDigits=128
springs.util.security.passwords.clients.minSpecials=1
springs.util.security.passwords.clients.maxSpecials=128
springs.util.security.passwords.clients.minWhitespace=0
springs.util.security.passwords.clients.maxWhitespace=0

springs.util.security.passwords.servers.minLength=43
springs.util.security.passwords.servers.maxLength=128
springs.util.security.passwords.servers.maxAnywhereRepeats=2
springs.util.security.passwords.servers.maxConsecutiveRepeats=2
springs.util.security.passwords.servers.firsts=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
springs.util.security.passwords.servers.lasts=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz

springs.util.security.passwords.servers.uppers=ABCDEFGHIJKLMNOPQRSTUVWXYZ
springs.util.security.passwords.servers.lowers=abcdefghijklmnopqrstuvwxyz
springs.util.security.passwords.servers.digits=0123456789
springs.util.security.passwords.servers.specials=~`!@#$%^&*()_-+={}[]|\\\"':;?/<>,.
springs.util.security.passwords.servers.whitespace=
springs.util.security.passwords.servers.minUppers=1
springs.util.security.passwords.servers.maxUppers=128
springs.util.security.passwords.servers.minLowers=1
springs.util.security.passwords.servers.maxLowers=128
springs.util.security.passwords.servers.minDigits=1
springs.util.security.passwords.servers.maxDigits=128
springs.util.security.passwords.servers.minSpecials=1
springs.util.security.passwords.servers.maxSpecials=128
springs.util.security.passwords.servers.minWhitespace=0
springs.util.security.passwords.servers.maxWhitespace=0
