springs.persistenceorm.clients.client[0].clientName=adminclient1
springs.persistenceorm.clients.client[0].secret=admin1password
springs.persistenceorm.clients.client[0].clientStatus=ACT
springs.persistenceorm.clients.client[0].clientType=ADM
springs.persistenceorm.clients.client[0].clientTimezones[0]=America/New_York

springs.persistenceorm.clients.client[1].clientName=operatorclient1
springs.persistenceorm.clients.client[1].secret=operator1password
springs.persistenceorm.clients.client[1].clientStatus=ACT
springs.persistenceorm.clients.client[1].clientType=OPR
springs.persistenceorm.clients.client[1].clientTimezones[0]=America/New_York

springs.persistenceorm.clients.client[2].clientName=userclient1
springs.persistenceorm.clients.client[2].secret=user1password
springs.persistenceorm.clients.client[2].clientStatus=ACT
springs.persistenceorm.clients.client[2].clientType=EMP
springs.persistenceorm.clients.client[2].clientTimezones[0]=America/New_York
