springs.persistenceorm.clients.client[0].clientName=adminclient1
springs.persistenceorm.clients.client[0].secret=admin1password
springs.persistenceorm.clients.client[0].status=ACT
springs.persistenceorm.clients.client[0].type=ADM
springs.persistenceorm.clients.client[0].timezones[0]=America/New_York

springs.persistenceorm.clients.client[1].clientName=operatorclient1
springs.persistenceorm.clients.client[1].secret=operator1password
springs.persistenceorm.clients.client[1].status=ACT
springs.persistenceorm.clients.client[1].type=OPR
springs.persistenceorm.clients.client[1].timezones[0]=America/New_York

springs.persistenceorm.clients.client[2].clientName=userclient1
springs.persistenceorm.clients.client[2].secret=user1password
springs.persistenceorm.clients.client[2].status=ACT
springs.persistenceorm.clients.client[2].type=EMP
springs.persistenceorm.clients.client[2].timezones[0]=America/New_York
