package com.github.justincranford.springs.persistenceorm.users.person.enums;

@SuppressWarnings({"nls", "hiding"})
public enum Salutation {
    DR("Dr", "Doctor"),
    MR("Mr", "Mister"),
    MRS("Mrs", "Missus"),
    MS("Ms", "Miss"),
    MX("Mx", "Gender-neutral"),
    PROF("Prof", "Professor"),
    SIR("Sir", "Sir"),
    MADAM("Madam", "Madam"),
    REV("Rev", "Reverend"),
    CAPT("Capt", "Captain"),
    MAJ("Maj", "Major"),
    COL("Col", "Colonel"),
    LT("Lt", "Lieutenant"),
    SGT("Sgt", "Sergeant"),
    DR_MRS("Dr. Mrs", "Doctor Missus"),
    DR_MS("Dr. Ms", "Doctor Miss"),
    HON("Hon", "Honorable"),
    SEN("Sen", "Senator"),
    JUDGE("Judge", "Judge"),
    AMB("Amb", "Ambassador"),
    DAME("Dame", "Dame"),
    BARON("Baron", "Baron"),
    BARONESS("Baroness", "Baroness"),
    LORD("Lord", "Lord"),
    LADY("Lady", "Lady"),
    COUNT("Count", "Count"),
    COUNTESS("Countess", "Countess"),
    GENERAL("Gen", "General"),
    CAPTAIN("Capt", "Captain"),
    COMMANDER("Cmdr", "Commander"),
    MAJOR_GENERAL("Maj Gen", "Major General"),
    ADMIRAL("Adm", "Admiral"),
    CHIEF("Chief", "Chief"),
    HEAD("Head", "Head"),
    MENTOR("Mentor", "Mentor"),
    PASTOR("Pastor", "Pastor"),
    FATHER("Fr", "Father"),
    MOTHER("Mother", "Mother"),
    SHEIKH("Sheikh", "Sheikh"),
    ELDER("Elder", "Elder"),
    SULTAN("Sultan", "Sultan"),
    RAJA("Raja", "Raja"),
    RANI("Rani", "Rani"),
    HEADMASTER("HM", "Headmaster"),
    COACH("Coach", "Coach"),
    CANDIDATE("Candidate", "Candidate"),
    VIP("VIP", "Very Important Person"),
    EXECUTIVE("Exec", "Executive"),
    DIRECTOR("Dir", "Director"),
    CEO("CEO", "Chief Executive Officer"),
    PRESIDENT("Pres", "President"),
    VICE_PRESIDENT("VP", "Vice President"),
    OFFICER("Officer", "Officer"),
    SPECIALIST("Spec", "Specialist"),
    ANALYST("Analyst", "Analyst"),
    DIRECTOR_GENERAL("Dir Gen", "Director General"),
    EMERITUS("Emeritus", "Emeritus"),
    PROFESSOR_EMERITUS("Prof Emeritus", "Professor Emeritus"),
    DOCTOR_OF_MEDICINE("MD", "Doctor of Medicine"),
    DOCTOR_OF_PHILOSOPHY("PhD", "Doctor of Philosophy"),
    DOCTOR_OF_LAW("JD", "Juris Doctor"),
    TEACHER("Tchr", "Teacher"),
    NURSE("Nurse", "Nurse"),
    COUNSELOR("Counselor", "Counselor"),
    THERAPIST("Therapist", "Therapist"),
    BISHOP("Bishop", "Bishop"),
    CARDINAL("Cardinal", "Cardinal"),
    ARCHBISHOP("Archbishop", "Archbishop"),
    MINISTER("Minister", "Minister"),
    REVEREND_FATHER("Fr", "Reverend Father"),
    REVEREND_MOTHER("Mother", "Reverend Mother"),
    FATHER_SUPERIOR("Fr. Sup", "Father Superior"),
    MASTER("Master", "Master"),
    LADY_SUPERIOR("Lady Sup", "Lady Superior"),
    VASSAL("Vassal", "Vassal"),
    EXECUTIVE_DIRECTOR("Exec Dir", "Executive Director"),
    OPERATIONS_MANAGER("Ops Mgr", "Operations Manager"),
    PROJECT_MANAGER("PM", "Project Manager"),
    PRODUCT_MANAGER("Prod Mgr", "Product Manager"),
    ACCOUNT_MANAGER("Acct Mgr", "Account Manager"),
    TEAM_LEADER("TL", "Team Leader"),
    ASSISTANT("Asst", "Assistant"),
    SPECIAL_ADVISOR("Spec Advisor", "Special Advisor"),
    HONORABLE_JUDGE("Hon. Judge", "Honorable Judge"),
    AMBASSADOR_EXTRAORDINARY("Amb. Extra", "Ambassador Extraordinary"),
    HIGH_COMMISSIONER("High Comm", "High Commissioner"),
    LEGATE("Legate", "Legate"),
    PROCONSUL("Proconsul", "Proconsul"),
    PREFECT("Prefect", "Prefect"),
    ATTACHE("Attaché", "Attaché"),
    CONSUL("Consul", "Consul"),
    SUBDIRECTOR("Subdir", "Subdirector"),
    FIRST_LIEUTENANT("1st Lt", "First Lieutenant"),
    SECOND_LIEUTENANT("2nd Lt", "Second Lieutenant"),
    LIEUTENANT_GENERAL("Lt Gen", "Lieutenant General"),
    AIRMARSHAL("Air Mshl", "Air Marshal"),
    COMMANDANT("Cmdt", "Commandant"),
    BRIGADIER("Brig", "Brigadier"),
    FLIGHT_LIEUTENANT("Flt Lt", "Flight Lieutenant"),
    CAPTAIN_GENERAL("Capt Gen", "Captain General"),
    SQUADRON_LEADER("Sqn Ldr", "Squadron Leader"),
    CHIEF_EXECUTIVE("CE", "Chief Executive"),
    MANAGING_DIRECTOR("MD", "Managing Director"),
    VICE_CHANCELLOR("VC", "Vice Chancellor"),
    DEAN("Dean", "Dean"),
    HEAD_OF_DEPARTMENT("HoD", "Head of Department"),
    LAB_MANAGER("Lab Mgr", "Laboratory Manager"),
    RESEARCH_DIRECTOR("Research Dir", "Research Director"),
    TRAINING_DIRECTOR("Training Dir", "Training Director"),
    PROGRAM_MANAGER("Prog Mgr", "Program Manager"),
    OPERATIONS_EXECUTIVE("Ops Exec", "Operations Executive"),
    BUSINESS_ANALYST("BA", "Business Analyst"),
    MARKETING_MANAGER("Mktg Mgr", "Marketing Manager"),
    SALES_DIRECTOR("Sales Dir", "Sales Director"),
    CHIEF_MARKETING_OFFICER("CMO", "Chief Marketing Officer"),
    CHIEF_FINANCIAL_OFFICER("CFO", "Chief Financial Officer"),
    CHIEF_OPERATING_OFFICER("COO", "Chief Operating Officer"),
    VICE_PRESIDENT_OF_SALES("VP Sales", "Vice President of Sales"),
    CHIEF_TECHNOLOGY_OFFICER("CTO", "Chief Technology Officer"),
    SOFTWARE_ENGINEER("Software Eng", "Software Engineer"),
    NETWORK_ENGINEER("Network Eng", "Network Engineer"),
    SYSTEMS_ANALYST("Sys Analyst", "Systems Analyst"),
    WEB_DEVELOPER("Web Dev", "Web Developer"),
    DATABASE_ADMINISTRATOR("DBA", "Database Administrator"),
    PROJECT_COORDINATOR("Proj Coord", "Project Coordinator"),
    TECHNICAL_SUPPORT("Tech Support", "Technical Support"),
    CUSTOMER_SERVICE_REP("CSR", "Customer Service Representative"),
    HUMAN_RESOURCES_MANAGER("HR Mgr", "Human Resources Manager"),
    TRAINER("Trainer", "Trainer"),
    EVENT_COORDINATOR("Event Coord", "Event Coordinator"),
    CONFERENCE_MANAGER("Conf Mgr", "Conference Manager"),
    RECRUITER("Recruiter", "Recruiter"),
    TALENT_ACQUISITION_MANAGER("TAM", "Talent Acquisition Manager"),
    LEGAL_ADVISOR("Legal Advisor", "Legal Advisor"),
    CORPORATE_LAWYER("Corp Lawyer", "Corporate Lawyer"),
    LITIGATION_ATTORNEY("Lit Attorney", "Litigation Attorney"),
    CRIMINAL_DEFENSE_ATTORNEY("Crim Def Attorney", "Criminal Defense Attorney"),
    FAMILY_LAWYER("Fam Lawyer", "Family Lawyer"),
    TAX_ATTORNEY("Tax Attorney", "Tax Attorney"),
    PATENT_ATTORNEY("Patent Attorney", "Patent Attorney"),
    IMMIGRATION_ATTORNEY("Imm Attorney", "Immigration Attorney"),
    PARALEGAL("Paralegal", "Paralegal"),
    LEGAL_SECRETARY("Legal Sec", "Legal Secretary"),
    ACCOUNTANT("Acct", "Accountant"),
    FINANCIAL_ANALYST("Fin Analyst", "Financial Analyst"),
    AUDITOR("Auditor", "Auditor"),
    CONTROLLER("Controller", "Controller"),
    TREASURER("Treasurer", "Treasurer"),
    FINANCE_MANAGER("Fin Mgr", "Finance Manager"),
    DATA_SCIENTIST("Data Sci", "Data Scientist"),
    DATA_ANALYST("Data Analyst", "Data Analyst"),
    STATISTICIAN("Statistician", "Statistician"),
    RESEARCH_ANALYST("Research Analyst", "Research Analyst"),
    OPERATIONS_ANALYST("Ops Analyst", "Operations Analyst"),
    MARKET_RESEARCH_ANALYST("Mktg Res Analyst", "Market Research Analyst"),
    JOURNALIST("Journo", "Journalist"),
    EDITOR("Editor", "Editor"),
    COLUMNIST("Columnist", "Columnist"),
    REPORTER("Reporter", "Reporter"),
    NEWS_ANCHOR("News Anchor", "News Anchor"),
    BROADCAST_JOURNALIST("Broadcast Journo", "Broadcast Journalist"),
    PUBLIC_RELATIONS_SPECIALIST("PR Spec", "Public Relations Specialist"),
    CONTENT_WRITER("Content Writer", "Content Writer"),
    COPYWRITER("Copywriter", "Copywriter"),
    SOCIAL_MEDIA_MANAGER("Social Media Mgr", "Social Media Manager"),
    GRAPHIC_DESIGNER("Graphic Designer", "Graphic Designer"),
    ART_DIRECTOR("Art Dir", "Art Director"),
    PHOTOGRAPHER("Photographer", "Photographer"),
    VIDEO_EDITOR("Video Editor", "Video Editor"),
    CREATIVE_DIRECTOR("Creative Dir", "Creative Director"),
    MARKETING_ANALYST("Mktg Analyst", "Marketing Analyst"),
    PRODUCT_DESIGNER("Prod Designer", "Product Designer"),
    UI_UX_DESIGNER("UI/UX Designer", "UI/UX Designer"),
    HR_BUSINESS_PARTNER("HRBP", "HR Business Partner"),
    OFFICE_MANAGER("Office Mgr", "Office Manager"),
    FACILITY_MANAGER("Facility Mgr", "Facility Manager"),
    RECEPTIONIST("Receptionist", "Receptionist"),
    EXECUTIVE_ASSISTANT("EA", "Executive Assistant"),
    PERSONAL_ASSISTANT("PA", "Personal Assistant"),
    OFFICE_COORDINATOR("Office Coord", "Office Coordinator"),
    OFFICE_CLEANER("Office Cleaner", "Office Cleaner"),
    SECURITY_GUARD("Security Guard", "Security Guard"),
    MAINTENANCE_WORKER("Maintenance Worker", "Maintenance Worker"),
    CATERER("Caterer", "Caterer"),
    CHEF("Chef", "Chef"),
    COOK("Cook", "Cook"),
    SERVER("Server", "Server"),
    BARISTA("Barista", "Barista"),
    WAITER("Waiter", "Waiter"),
    BARTENDER("Bartender", "Bartender"),
    FRONT_DESK_MANAGER("Front Desk Mgr", "Front Desk Manager"),
    FRONT_DESK_CLERK("Front Desk Clerk", "Front Desk Clerk"),
    TRAVEL_AGENT("Travel Agent", "Travel Agent"),
    FLIGHT_ATTENDANT("Flight Attendant", "Flight Attendant"),
    AIRLINE_PILOT("Pilot", "Airline Pilot"),
    CONDUCTOR("Conductor", "Conductor"),
    BUS_DRIVER("Bus Driver", "Bus Driver"),
    RAILWAY_STATION_MANAGER("Station Mgr", "Railway Station Manager"),
    SCHOOL_PRINCIPAL("Principal", "School Principal"),
    ASSISTANT_PRINCIPAL("Asst Principal", "Assistant Principal"),
    SCHOOL_COUNSELOR("School Counselor", "School Counselor"),
    COORDINATOR("Coordinator", "Coordinator"),
    STUDENT("Student", "Student"),
    ALUMNUS("Alumnus", "Alumnus"),
    POSTGRADUATE("Postgraduate", "Postgraduate"),
    UNDERGRADUATE("Undergraduate", "Undergraduate"),
    GUEST_LECTURER("Guest Lecturer", "Guest Lecturer"),
    INTERNSHIP_SUPERVISOR("Internship Sup", "Internship Supervisor"),
    GUEST_SPEAKER("Guest Speaker", "Guest Speaker"),
    FACULTY_ADVISOR("Faculty Advisor", "Faculty Advisor"),
    ASSISTANT_INSTRUCTOR("Asst Instructor", "Assistant Instructor"),
    LAB_TECHNICIAN("Lab Tech", "Laboratory Technician"),
    RESEARCH_FELLOW("Research Fellow", "Research Fellow"),
    GRADUATE_STUDENT("Grad Student", "Graduate Student"),
    UNDERGRADUATE_STUDENT("Undergrad Student", "Undergraduate Student"),
    DOCTORAL_STUDENT("Doctoral Student", "Doctoral Student"),
    POSTDOC("Postdoc", "Postdoctoral Fellow"),
    THESIS_SUPERVISOR("Thesis Sup", "Thesis Supervisor"),
    RESEARCH_ASSOCIATE("Research Associate", "Research Associate"),
    FIELD_RESEARCHER("Field Researcher", "Field Researcher"),
    DATA_COLLECTION_MANAGER("Data Collection Mgr", "Data Collection Manager"),
    STATISTICAL_ANALYST("Statistical Analyst", "Statistical Analyst"),
    QUANTITATIVE_ANALYST("Quant Analyst", "Quantitative Analyst"),
    QUALITATIVE_ANALYST("Qual Analyst", "Qualitative Analyst"),
    COMPLIANCE_OFFICER("Compliance Officer", "Compliance Officer"),
    RISK_MANAGER("Risk Manager", "Risk Manager"),
    AUDIT_MANAGER("Audit Mgr", "Audit Manager"),
    INSURANCE_AGENT("Insurance Agent", "Insurance Agent"),
    CLAIMS_ADJUSTER("Claims Adjuster", "Claims Adjuster"),
    FINANCIAL_ADVISOR("Fin Advisor", "Financial Advisor"),
    INVESTMENT_ANALYST("Invest Analyst", "Investment Analyst"),
    STOCK_BROKER("Stock Broker", "Stock Broker"),
    TRADING_ANALYST("Trading Analyst", "Trading Analyst"),
    RISK_ANALYST("Risk Analyst", "Risk Analyst"),
    COMMODITIES_TRADER("Commodities Trader", "Commodities Trader"),
    FISCAL_ANALYST("Fiscal Analyst", "Fiscal Analyst"),
    ENERGY_ANALYST("Energy Analyst", "Energy Analyst"),
    SOCIAL_WORKER("Social Worker", "Social Worker"),
    COMMUNITY_ORGANIZER("Community Organizer", "Community Organizer"),
    NONPROFIT_MANAGER("Nonprofit Mgr", "Nonprofit Manager"),
    CHARITY_WORKER("Charity Worker", "Charity Worker"),
    VOLUNTEER_COORDINATOR("Volunteer Coord", "Volunteer Coordinator"),
    GRANT_WRITER("Grant Writer", "Grant Writer"),
    FUNDRAISER("Fundraiser", "Fundraiser"),
    ADVOCATE("Advocate", "Advocate"),
    STRATEGIST("Strategist", "Strategist"),
    COUNCIL_MEMBER("Council Member", "Council Member"),
    MAYOR("Mayor", "Mayor"),
    CITY_MANAGER("City Mgr", "City Manager"),
    COUNTY_EXECUTIVE("County Exec", "County Executive"),
    GOVERNOR("Governor", "Governor"),
    STATE_LEGISLATOR("State Legislator", "State Legislator"),
    CONGRESSPERSON("Congressperson", "Congressperson"),
    SENATOR("Senator", "Senator"),
    REPRESENTATIVE("Rep", "Representative"),
    FEDERAL_OFFICIAL("Fed Official", "Federal Official"),
    AMBASSADOR("Ambassador", "Ambassador"),
    MINISTER_OF_FINANCE("Fin Min", "Minister of Finance"),
    SECRETARY_OF_STATE("Sec of State", "Secretary of State"),
    PRESIDENT_OF_COUNTRY("Pres of Country", "President of Country"),
    PRIME_MINISTER("PM", "Prime Minister"),
    CHANCELLOR("Chancellor", "Chancellor"),
    CABINET_MEMBER("Cabinet Member", "Cabinet Member"),
    TRADE_REPRESENTATIVE("Trade Rep", "Trade Representative"),
    AMBASSADOR_PLENIPOTENTIARY("Amb. Plen", "Ambassador Plenipotentiary"),
    AMBASSADOR_AT_LARGE("Amb. At Large", "Ambassador at Large"),
    SPECIAL_ENVOY("Special Envoy", "Special Envoy"),
    INTERNATIONAL_DELEGATE("Int'l Delegate", "International Delegate"),
    FOREIGN_AFFAIRS_SPECIALIST("FA Specialist", "Foreign Affairs Specialist"),
    ECONOMIC_ADVISOR("Economic Advisor", "Economic Advisor"),
    SECURITY_ADVISOR("Security Advisor", "Security Advisor"),
    TECHNICAL_ADVISOR("Technical Advisor", "Technical Advisor"),
    MEDICAL_ADVISOR("Medical Advisor", "Medical Advisor"),
    SCIENCE_ADVISOR("Science Advisor", "Science Advisor"),
    CULTURAL_ADVISOR("Cultural Advisor", "Cultural Advisor"),
    ENVIRONMENTAL_ADVISOR("Env. Advisor", "Environmental Advisor"),
    PUBLIC_POLICY_ADVISOR("Public Policy Advisor", "Public Policy Advisor"),
    STRATEGIC_PLANNER("Strategic Planner", "Strategic Planner"),
    POLICY_ANALYST("Policy Analyst", "Policy Analyst"),
    COMMUNITY_DEVELOPER("Community Developer", "Community Developer"),
    URBAN_PLANNER("Urban Planner", "Urban Planner"),
    ARCHITECT("Architect", "Architect"),
    LANDSCAPE_ARCHITECT("Landscape Arch", "Landscape Architect"),
    INTERIOR_DESIGNER("Interior Designer", "Interior Designer"),
    CIVIL_ENGINEER("Civil Eng", "Civil Engineer"),
    MECHANICAL_ENGINEER("Mech Eng", "Mechanical Engineer"),
    ELECTRICAL_ENGINEER("Electrical Eng", "Electrical Engineer"),
    SOFTWARE_DEVELOPER("Software Dev", "Software Developer"),
    HARDWARE_ENGINEER("Hardware Eng", "Hardware Engineer"),
    SYSTEMS_ENGINEER("Systems Eng", "Systems Engineer"),
    TEST_ENGINEER("Test Eng", "Test Engineer"),
    APPLICATION_DEVELOPER("App Dev", "Application Developer"),
    WEB_DESIGNER("Web Designer", "Web Designer"),
    DATA_ENGINEER("Data Eng", "Data Engineer"),
    NETWORK_ADMINISTRATOR("Network Admin", "Network Administrator"),
    SYSTEM_ADMINISTRATOR("Sys Admin", "System Administrator"),
    IT_SUPPORT_SPECIALIST("IT Support", "IT Support Specialist"),
    DATABASE_DEVELOPER("DB Dev", "Database Developer"),
    BUSINESS_INTELLIGENCE_ANALYST("BI Analyst", "Business Intelligence Analyst"),
    IT_PROJECT_MANAGER("IT PM", "IT Project Manager"),
    ECOMMERCE_MANAGER("eComm Mgr", "E-commerce Manager"),
    SOCIAL_MEDIA_SPECIALIST("Social Media Spec", "Social Media Specialist"),
    DIGITAL_MARKETING_MANAGER("Digital Mktg Mgr", "Digital Marketing Manager"),
    CONTENT_MARKETING_MANAGER("Content Mktg Mgr", "Content Marketing Manager"),
    SEO_SPECIALIST("SEO Spec", "SEO Specialist"),
    PPC_SPECIALIST("PPC Spec", "PPC Specialist"),
    EMAIL_MARKETING_MANAGER("Email Mktg Mgr", "Email Marketing Manager"),
    AFFILIATE_MARKETING_MANAGER("Affiliate Mktg Mgr", "Affiliate Marketing Manager"),
    COMMUNITY_MANAGER("Community Mgr", "Community Manager"),
    ANALYTICS_MANAGER("Analytics Mgr", "Analytics Manager"),
    USER_EXPERIENCE_RESEARCHER("UX Researcher", "User Experience Researcher"),
    USER_INTERFACE_DEVELOPER("UI Developer", "User Interface Developer"),
    VIRTUAL_ASSISTANT("VA", "Virtual Assistant"),
    PROJECT_ASSISTANT("Project Asst", "Project Assistant"),
    SALES_ASSOCIATE("Sales Associate", "Sales Associate"),
    STORE_MANAGER("Store Mgr", "Store Manager"),
    DISTRICT_MANAGER("District Mgr", "District Manager"),
    REGIONAL_MANAGER("Regional Mgr", "Regional Manager"),
    VICE_PRESIDENT_OF_HUMAN_RESOURCES("VP HR", "Vice President of Human Resources"),
    PROCUREMENT_MANAGER("Procurement Mgr", "Procurement Manager"),
    SUPPLY_CHAIN_MANAGER("Supply Chain Mgr", "Supply Chain Manager"),
    LOGISTICS_MANAGER("Logistics Mgr", "Logistics Manager"),
    CUSTOMER_SUCCESS_MANAGER("CSM", "Customer Success Manager"),
    CLIENT_SERVICES_MANAGER("Client Services Mgr", "Client Services Manager"),
    PRODUCT_QUALITY_MANAGER("Product Quality Mgr", "Product Quality Manager"),
    HEALTHCARE_MANAGER("Healthcare Mgr", "Healthcare Manager"),
    HEALTHCARE_ADMINISTRATOR("Healthcare Admin", "Healthcare Administrator"),
    CLINICAL_DIRECTOR("Clinical Dir", "Clinical Director"),
    MEDICAL_DIRECTOR("Medical Dir", "Medical Director"),
    PHYSICIAN_ASSISTANT("PA", "Physician Assistant"),
    PHARMACIST("Pharmacist", "Pharmacist"),
    NURSE_PRACTITIONER("NP", "Nurse Practitioner"),
    REGISTERED_NURSE("RN", "Registered Nurse"),
    LICENSED_PRACTICAL_NURSE("LPN", "Licensed Practical Nurse"),
    CERTIFIED_NURSING_ASSISTANT("CNA", "Certified Nursing Assistant"),
    MEDICAL_TECHNICIAN("Med Tech", "Medical Technician"),
    RESPIRATORY_THERAPIST("Respiratory Therapist", "Respiratory Therapist"),
    RADIOLOGIC_TECHNOLOGIST("Radiologic Tech", "Radiologic Technologist"),
    DENTIST("Dentist", "Dentist"),
    ORTHODONTIST("Orthodontist", "Orthodontist"),
    VETERINARIAN("Vet", "Veterinarian"),
    ANIMAL_TECHNICIAN("Animal Tech", "Animal Technician"),
    DENTAL_HYGIENIST("Dental Hygienist", "Dental Hygienist"),
    PHYSICAL_THERAPIST("PT", "Physical Therapist"),
    OCCUPATIONAL_THERAPIST("OT", "Occupational Therapist"),
    SPEECH_LANGUAGE_PATHOLOGIST("SLP", "Speech Language Pathologist"),
    SOCIAL_SERVICES_MANAGER("Social Services Mgr", "Social Services Manager"),
    PSYCHOLOGIST("Psychologist", "Psychologist"),
    CLINICAL_SOCIAL_WORKER("Clinical SW", "Clinical Social Worker"),
    BEHAVIOR_ANALYST("Behavior Analyst", "Behavior Analyst"),
    MENTAL_HEALTH_COUNSELOR("Mental Health Counselor", "Mental Health Counselor"),
    SCHOOL_SOCIAL_WORKER("School SW", "School Social Worker"),
    SCHOOL_PSYCHOLOGIST("School Psychologist", "School Psychologist"),
    REHABILITATION_COUNSELOR("Rehab Counselor", "Rehabilitation Counselor"),
    PARENTING_COORDINATOR("Parenting Coordinator", "Parenting Coordinator"),
    ALTERNATIVE_DISPUTE_RESOLUTION_SPECIALIST("ADR Specialist", "Alternative Dispute Resolution Specialist"),
    SOCIAL_SERVICES_COORDINATOR("Social Services Coord", "Social Services Coordinator"),
    CLINICAL_MANAGER("Clinical Mgr", "Clinical Manager"),
    SYSTEMS_THINKER("Systems Thinker", "Systems Thinker"),
    STRATEGIC_THINKER("Strategic Thinker", "Strategic Thinker"),
    CREATIVE_THINKER("Creative Thinker", "Creative Thinker"),
    CRITICAL_THINKER("Critical Thinker", "Critical Thinker"),
    PROBLEM_SOLVER("Problem Solver", "Problem Solver"),
    DECISION_MAKER("Decision Maker", "Decision Maker"),
    INNOVATOR("Innovator", "Innovator"),
    CHANGE_AGENT("Change Agent", "Change Agent"),
    TEAM_BUILDER("Team Builder", "Team Builder"),
    RELATIONSHIP_BUILDER("Relationship Builder", "Relationship Builder"),
    NETWORKING_SPECIALIST("Networking Spec", "Networking Specialist"),
    PROFESSIONAL_DEVELOPER("Prof Dev", "Professional Developer"),
    EXECUTIVE_COACH("Exec Coach", "Executive Coach"),
    LEADERSHIP_DEVELOPER("Leadership Dev", "Leadership Developer"),
    SUCCESS_COACH("Success Coach", "Success Coach"),
    BUSINESS_MENTOR("Biz Mentor", "Business Mentor"),
    CAREER_COACH("Career Coach", "Career Coach"),
    COMMUNICATIONS_COACH("Communications Coach", "Communications Coach"),
    FINANCIAL_COACH("Financial Coach", "Financial Coach"),
    HEALTH_COACH("Health Coach", "Health Coach"),
    LIFE_COACH("Life Coach", "Life Coach"),
    YOGA_INSTRUCTOR("Yoga Instructor", "Yoga Instructor"),
    PERSONAL_TRAINER("PT", "Personal Trainer"),
    FITNESS_INSTRUCTOR("Fitness Instructor", "Fitness Instructor"),
    WELLNESS_COACH("Wellness Coach", "Wellness Coach"),
    SPIRITUAL_GUIDE("Spiritual Guide", "Spiritual Guide"),
    MEDITATION_TEACHER("Meditation Teacher", "Meditation Teacher"),
    MINDFULNESS_INSTRUCTOR("Mindfulness Instructor", "Mindfulness Instructor"),
    COUNSELOR_OF_LIFE("Counselor of Life", "Counselor of Life"),
    LIFE_SCHOOL("Life School", "Life School"),
    LIFE_EXPERT("Life Expert", "Life Expert"),
    COMMUNITY_HEALTH_WORKER("Community Health Worker", "Community Health Worker"),
    HEALTH_PROMOTER("Health Promoter", "Health Promoter"),
    PEER_SUPPORT_WORKER("Peer Support Worker", "Peer Support Worker"),
    SOCIAL_WORKER_SUPERVISOR("Social Worker Sup", "Social Worker Supervisor"),
    YOUTH_WORKER("Youth Worker", "Youth Worker"),
    AGING_SERVICES_WORKER("Aging Services Worker", "Aging Services Worker"),
    DISABILITY_SERVICES_WORKER("Disability Services Worker", "Disability Services Worker"),
    HOME_HEALTH_AIDE("Home Health Aide", "Home Health Aide"),
    HOSPICE_WORKER("Hospice Worker", "Hospice Worker"),
    ADOPTION_WORKER("Adoption Worker", "Adoption Worker"),
    CANCER_SUPPORT_WORKER("Cancer Support Worker", "Cancer Support Worker"),
    SUBSTANCE_ABUSE_COUNSELOR("Substance Abuse Counselor", "Substance Abuse Counselor"),
    MENTAL_HEALTH_WORKER("Mental Health Worker", "Mental Health Worker"),
    DOMESTIC_VIOLENCE_ADVOCATE("DV Advocate", "Domestic Violence Advocate"),
    SEXUAL_ASSAULT_ADVOCATE("SA Advocate", "Sexual Assault Advocate"),
    VICTIM_ADVOCATE("Victim Advocate", "Victim Advocate"),
    TRAUMA_INFORMED_SPECIALIST("Trauma Informed Spec", "Trauma Informed Specialist"),
    NEIGHBORHOOD_COORDINATOR("Neighborhood Coord", "Neighborhood Coordinator"),
    NONPROFIT_VOLUNTEER("Nonprofit Volunteer", "Nonprofit Volunteer"),
    SOCIAL_CHANGE_AGENT("Social Change Agent", "Social Change Agent"),
    GRASSROOTS_ACTIVIST("Grassroots Activist", "Grassroots Activist"),
    PUBLIC_INTEREST_ADVOCATE("Public Interest Advocate", "Public Interest Advocate"),
    HUMAN_RIGHTS_ADVOCATE("Human Rights Advocate", "Human Rights Advocate"),
    ENVIRONMENTAL_ADVOCATE("Environmental Advocate", "Environmental Advocate"),
    EDUCATION_ADVOCATE("Education Advocate", "Education Advocate"),
    VOTER_REGISTRATION_SPECIALIST("Voter Reg Specialist", "Voter Registration Specialist"),
    CITIZEN_ACTION_LEADER("Citizen Action Leader", "Citizen Action Leader"),
    CIVIL_RIGHTS_LEADER("Civil Rights Leader", "Civil Rights Leader"),
    ANTI_POVERTY_ACTIVIST("Anti-Poverty Activist", "Anti-Poverty Activist"),
    LABOR_UNION_LEADER("Labor Union Leader", "Labor Union Leader"),
    INTERNATIONAL_AFFAIRS_SPECIALIST("Int'l Affairs Spec", "International Affairs Specialist"),
    GLOBAL_HEALTH_SPECIALIST("Global Health Specialist", "Global Health Specialist"),
    PUBLIC_HEALTH_SPECIALIST("Public Health Specialist", "Public Health Specialist"),
    HUMAN_RESOURCES_SPECIALIST("HR Specialist", "Human Resources Specialist"),
    EMPLOYEE_RELATIONS_SPECIALIST("ER Specialist", "Employee Relations Specialist"),
    COMPENSATION_ANALYST("Comp Analyst", "Compensation Analyst"),
    BENEFITS_SPECIALIST("Benefits Specialist", "Benefits Specialist"),
    TALENT_MANAGEMENT_SPECIALIST("Talent Mgt Spec", "Talent Management Specialist"),
    WORKFORCE_PLANNING_ANALYST("Workforce Planning Analyst", "Workforce Planning Analyst"),
    TRAINING_AND_DEVELOPMENT_MANAGER("T&D Mgr", "Training and Development Manager"),
    LEARNING_AND_DEVELOPMENT_MANAGER("L&D Mgr", "Learning and Development Manager"),
    ORGANIZATIONAL_DEVELOPMENT_SPECIALIST("OD Specialist", "Organizational Development Specialist"),
    CHANGE_MANAGEMENT_SPECIALIST("Change Mgt Spec", "Change Management Specialist"),
    DIVERSITY_AND_INCLUSION_MANAGER("D&I Mgr", "Diversity and Inclusion Manager"),
    EMPLOYEE_ENGAGEMENT_SPECIALIST("EE Engagement Spec", "Employee Engagement Specialist"),
    EMPLOYEE_WELLNESS_COORDINATOR("Wellness Coord", "Employee Wellness Coordinator"),
    WORKPLACE_SAFETY_SPECIALIST("Workplace Safety Specialist", "Workplace Safety Specialist"),
    CULTURE_MANAGER("Culture Mgr", "Culture Manager"),
    ENVIRONMENTAL_SCIENTIST("Environmental Scientist", "Environmental Scientist"),
    GEOLOGIST("Geologist", "Geologist"),
    OCEANOGRAPHER("Oceanographer", "Oceanographer"),
    METEOROLOGIST("Meteorologist", "Meteorologist"),
    CLIMATOLOGIST("Climatologist", "Climatologist"),
    ATMOSPHERIC_SCIENTIST("Atmospheric Scientist", "Atmospheric Scientist"),
    ECOLOGIST("Ecologist", "Ecologist"),
    CONSERVATION_BIOLOGIST("Conservation Biologist", "Conservation Biologist"),
    WILDLIFE_BIOLOGIST("Wildlife Biologist", "Wildlife Biologist"),
    ZOOLOGIST("Zoologist", "Zoologist"),
    MARINE_BIOLOGIST("Marine Biologist", "Marine Biologist"),
    BIOLOGIST("Biologist", "Biologist"),
    BIOCHEMIST("Biochemist", "Biochemist"),
    MOLECULAR_BIOLOGIST("Molecular Biologist", "Molecular Biologist"),
    GENETICIST("Geneticist", "Geneticist"),
    PHYSICIST("Physicist", "Physicist"),
    CHEMIST("Chemist", "Chemist"),
    ANTHROPOLOGIST("Anthropologist", "Anthropologist"),
    SOCIOLOGIST("Sociologist", "Sociologist"),
    ARCHAEOLOGIST("Archaeologist", "Archaeologist"),
    HISTORIAN("Historian", "Historian"),
    PHILOSOPHER("Philosopher", "Philosopher"),
    CULTURAL_ANTHROPOLOGIST("Cultural Anthropologist", "Cultural Anthropologist"),
    ECONOMIST("Economist", "Economist"),
    POLITICAL_SCIENTIST("Political Scientist", "Political Scientist"),
    ETHICIST("Ethicist", "Ethicist"),
    CLASSICAL_SCHOLAR("Classical Scholar", "Classical Scholar"),
    LITERARY_CRITIC("Literary Critic", "Literary Critic"),
    ART_CRITIC("Art Critic", "Art Critic"),
    THEATER_CRITIC("Theater Critic", "Theater Critic"),
    FILM_CRITIC("Film Critic", "Film Critic"),
    MUSICOLOGIST("Musicologist", "Musicologist"),
    THEOLOGIAN("Theologian", "Theologian"),
    ARCHITECTURAL_HISTORIAN("Architectural Historian", "Architectural Historian"),
    FOOD_CRITIC("Food Critic", "Food Critic"),
    PERFORMANCE_ART_CRITIC("Performance Art Critic", "Performance Art Critic"),
    DANCE_CRITIC("Dance Critic", "Dance Critic"),
    LITERARY_AGENT("Literary Agent", "Literary Agent"),
    BOOK_EDITOR("Book Editor", "Book Editor"),
    MOVIE_PRODUCER("Movie Producer", "Movie Producer"),
    TELEVISION_PRODUCER("Television Producer", "Television Producer"),
    RADIO_PRODUCER("Radio Producer", "Radio Producer"),
    DOCUMENTARY_FILMMAKER("Documentary Filmmaker", "Documentary Filmmaker"),
    SCREENWRITER("Screenwriter", "Screenwriter"),
    NOVELIST("Novelist", "Novelist"),
    POET("Poet", "Poet"),
    PLAYWRIGHT("Playwright", "Playwright"),
    ARTIST("Artist", "Artist"),
    PHOTOGRAPHIC_ARTIST("Photographic Artist", "Photographic Artist"),
    GRAPHIC_NOVELIST("Graphic Novelist", "Graphic Novelist"),
    SCULPTOR("Sculptor", "Sculptor"),
    MUSICIAN("Musician", "Musician"),
    SONGWRITER("Songwriter", "Songwriter"),
    DANCER("Dancer", "Dancer"),
    PERFORMER("Performer", "Performer"),
    COMPOSER("Composer", "Composer"),
    ART_COLLECTOR("Art Collector", "Art Collector"),
    MUSEUM_CURATOR("Museum Curator", "Museum Curator"),
    EXHIBITION_DESIGNER("Exhibition Designer", "Exhibition Designer"),
    GALLERY_OWNER("Gallery Owner", "Gallery Owner"),
    ARCHITECTURAL_DESIGNER("Architectural Designer", "Architectural Designer"),
    INTERIOR_DECORATOR("Interior Decorator", "Interior Decorator"),
    CRAFT_ARTIST("Craft Artist", "Craft Artist"),
    THEATER_DIRECTOR("Theater Director", "Theater Director"),
    FILM_DIRECTOR("Film Director", "Film Director"),
    MUSIC_DIRECTOR("Music Director", "Music Director"),
    DANCE_DIRECTOR("Dance Director", "Dance Director"),
    ART_TEACHER("Art Teacher", "Art Teacher"),
    MUSIC_TEACHER("Music Teacher", "Music Teacher"),
    DRAMA_TEACHER("Drama Teacher", "Drama Teacher"),
    DANCE_TEACHER("Dance Teacher", "Dance Teacher"),
    ART_TUTOR("Art Tutor", "Art Tutor"),
    MUSIC_TUTOR("Music Tutor", "Music Tutor"),
    DRAMA_TUTOR("Drama Tutor", "Drama Tutor"),
    DANCE_TUTOR("Dance Tutor", "Dance Tutor"),
    ART_HISTORIAN("Art Historian", "Art Historian"),
    MUSIC_HISTORIAN("Music Historian", "Music Historian"),
    DANCE_HISTORIAN("Dance Historian", "Dance Historian"),
    THEATER_HISTORIAN("Theater Historian", "Theater Historian"),
    CRITIC("Critic", "Critic"),
    ACADEMIC("Academic", "Academic"),
    CURATOR("Curator", "Curator"),
    PROGRAM_DIRECTOR("Program Director", "Program Director"),
    INITIATIVE_COORDINATOR("Initiative Coord", "Initiative Coordinator"),
    CONFERENCER("Conferencer", "Conferencer"),
    WEBINAR_HOST("Webinar Host", "Webinar Host"),
    WEBCASTER("Webcaster", "Webcaster"),
    BROADCASTER("Broadcaster", "Broadcaster"),
    DOCUMENTARY_NARRATOR("Documentary Narrator", "Documentary Narrator"),
    VOICE_OVER_ARTIST("Voice Over Artist", "Voice Over Artist"),
    AUDIO_ENGINEER("Audio Engineer", "Audio Engineer"),
    SOUND_DESIGNER("Sound Designer", "Sound Designer"),
    MUSIC_PRODUCER("Music Producer", "Music Producer"),
    ORCHESTRATOR("Orchestrator", "Orchestrator"),
    MUSIC_TECHNOLOGIST("Music Technologist", "Music Technologist"),
    TECHNICAL_DIRECTOR("Technical Director", "Technical Director"),
    PROGRAMMER("Programmer", "Programmer"),
    COMPUTER_SCIENTIST("Computer Scientist", "Computer Scientist"),
    ARTIFICIAL_INTELLIGENCE_ENGINEER("AI Engineer", "Artificial Intelligence Engineer"),
    INFORMATION_ARCHITECT("Information Architect", "Information Architect"),
    SYSTEM_ARCHITECT("System Architect", "System Architect"),
    CLOUD_ARCHITECT("Cloud Architect", "Cloud Architect"),
    DEVOPS_ENGINEER("DevOps Engineer", "DevOps Engineer"),
    CYBERSECURITY_SPECIALIST("Cybersecurity Specialist", "Cybersecurity Specialist"),
    BLOCKCHAIN_DEVELOPER("Blockchain Developer", "Blockchain Developer"),
    TECH_SUPPORT_ENGINEER("Tech Support Engineer", "Tech Support Engineer"),
    RESEARCH_DEVELOPER("Research Developer", "Research Developer"),
    FIELD_SERVICE_ENGINEER("Field Service Engineer", "Field Service Engineer"),
    SOFTWARE_QUALITY_ENGINEER("Software Quality Engineer", "Software Quality Engineer"),
    GAME_DEVELOPER("Game Developer", "Game Developer"),
    VIRTUAL_REALITY_DEVELOPER("VR Developer", "Virtual Reality Developer"),
    AUGMENTED_REALITY_DEVELOPER("AR Developer", "Augmented Reality Developer"),
    ROBOTICS_ENGINEER("Robotics Engineer", "Robotics Engineer"),
    GAME_DESIGNER("Game Designer", "Game Designer"),
    GAME_TESTER("Game Tester", "Game Tester"),
    GAME_WRITER("Game Writer", "Game Writer"),
    UI_DEVELOPER("UI Developer", "UI Developer"),
    GAME_NARRATIVE_DESIGNER("Game Narrative Designer", "Game Narrative Designer"),
    USER_INTERFACE_DESIGNER("UI Designer", "User Interface Designer"),
    GAME_GRAPHIC_ARTIST("Game Graphic Artist", "Game Graphic Artist"),
    GAME_MUSIC_COMPOSER("Game Music Composer", "Game Music Composer"),
    LEVEL_DESIGNER("Level Designer", "Level Designer"),
    TECHNICAL_ARTIST("Technical Artist", "Technical Artist"),
    ART_CONCEPTUALIZER("Art Conceptualizer", "Art Conceptualizer"),
    NARRATIVE_DESIGNER("Narrative Designer", "Narrative Designer"),
    ANIMATOR("Animator", "Animator"),
    VISUAL_EFFECTS_ARTIST("VFX Artist", "Visual Effects Artist"),
    CHARACTER_MODELER("Character Modeler", "Character Modeler"),
    ENVIRONMENT_ARTIST("Environment Artist", "Environment Artist"),
    RIGGER("Rigger", "Rigger"),
    LIGHTING_ARTIST("Lighting Artist", "Lighting Artist"),
    SCRIPT_WRITER("Script Writer", "Script Writer"),
    COMPOSITOR("Compositor", "Compositor"),
    MOTION_GRAPHIC_DESIGNER("Motion Graphic Designer", "Motion Graphic Designer"),
    BRAND_STRATEGIST("Brand Strategist", "Brand Strategist"),
    SOCIAL_MEDIA_STRATEGIST("Social Media Strategist", "Social Media Strategist"),
    EMAIL_MARKETING_SPECIALIST("Email Marketing Specialist", "Email Marketing Specialist"),
    DIGITAL_MEDIA_BUYER("Digital Media Buyer", "Digital Media Buyer"),
    FRONT_END_DEVELOPER("Front-End Developer", "Front-End Developer"),
    BACK_END_DEVELOPER("Back-End Developer", "Back-End Developer"),
    FULL_STACK_DEVELOPER("Full-Stack Developer", "Full-Stack Developer"),
    MOBILE_APP_DEVELOPER("Mobile App Developer", "Mobile App Developer"),
    SYSTEMS_ADMINISTRATOR("Sys Admin", "Systems Administrator"),
    SECURITY_ADMINISTRATOR("Security Admin", "Security Administrator"),
    TECHNICAL_WRITER("Technical Writer", "Technical Writer"),
    CONTENT_STRATEGIST("Content Strategist", "Content Strategist"),
    INFORMATION_SECURITY_ANALYST("InfoSec Analyst", "Information Security Analyst"),
    NETWORK_SECURITY_SPECIALIST("Network Security Specialist", "Network Security Specialist"),
    CLOUD_ENGINEER("Cloud Engineer", "Cloud Engineer"),
    COMPUTER_PROGRAMMER("Computer Programmer", "Computer Programmer"),
    PRODUCT_DEVELOPER("Product Developer", "Product Developer"),
    APPLICATION_SUPPORT_ANALYST("App Support Analyst", "Application Support Analyst"),
    TECHNICAL_SUPPORT_ENGINEER("Tech Support Engineer", "Technical Support Engineer"),
    SOFTWARE_ARCHITECT("Software Architect", "Software Architect"),
    UX_DESIGNER("UX Designer", "User Experience Designer"),
    DATA_VISUALIZATION_SPECIALIST("Data Visualization Specialist", "Data Visualization Specialist"),
    CUSTOMER_INSIGHTS_ANALYST("Customer Insights Analyst", "Customer Insights Analyst"),
    UX_WRITER("UX Writer", "User Experience Writer"),
    CONSUMER_BEHAVIOR_ANALYST("Consumer Behavior Analyst", "Consumer Behavior Analyst"),
    DIGITAL_PRODUCT_MANAGER("Digital Product Manager", "Digital Product Manager"),
    PUBLIC_RELATIONS_MANAGER("PR Manager", "Public Relations Manager"),
    BRAND_MANAGER("Brand Manager", "Brand Manager"),
    SEO_MANAGER("SEO Manager", "SEO Manager"),
    PPC_MANAGER("PPC Manager", "PPC Manager"),
    RADIOLOGIC_TECHNICIAN("Radiologic Tech", "Radiologic Technician"),
    FAMILY_THERAPIST("Family Therapist", "Family Therapist"),
    CLINICAL_CARE_COORDINATOR("Clinical Care Coord", "Clinical Care Coordinator"),
    BEHAVIORAL_HEALTH_MANAGER("Behavioral Health Manager", "Behavioral Health Manager"),
    PATIENT_NAVIGATOR("Patient Navigator", "Patient Navigator"),
    ADULT_DAY_CARE_WORKER("Adult Day Care Worker", "Adult Day Care Worker"),
    ASSISTED_LIVING_WORKER("Assisted Living Worker", "Assisted Living Worker"),
    SENIOR_CARE_WORKER("Senior Care Worker", "Senior Care Worker"),
    DISABILITY_SUPPORT_WORKER("Disability Support Worker", "Disability Support Worker"),
    CHILD_DEVELOPMENT_WORKER("Child Development Worker", "Child Development Worker"),
    SCHOOL_NURSE("School Nurse", "School Nurse"),
    PRIMARY_CARE_PROVIDER("PCP", "Primary Care Provider"),
    EMERGENCY_MEDICAL_TECHNICIAN("EMT", "Emergency Medical Technician"),
    PARAMEDIC("Paramedic", "Paramedic"),
    FIREFIGHTER("Firefighter", "Firefighter"),
    POLICE_OFFICER("Police Officer", "Police Officer"),
    CORRECTIONAL_OFFICER("Correctional Officer", "Correctional Officer"),
    ATTORNEY("Attorney", "Attorney"),
    LEGAL_AID("Legal Aid", "Legal Aid"),
    COURT_REPORTER("Court Reporter", "Court Reporter"),
    CORPORATE_COUNSEL("Corporate Counsel", "Corporate Counsel"),
    FAMILY_LAW_ATTORNEY("Family Law Attorney", "Family Law Attorney"),
    PERSONAL_INJURY_ATTORNEY("Personal Injury Attorney", "Personal Injury Attorney"),
    ESTATE_PLANNING_ATTORNEY("Estate Planning Attorney", "Estate Planning Attorney"),
    INTELLECTUAL_PROPERTY_ATTORNEY("Intellectual Property Attorney", "Intellectual Property Attorney"),
    ADMINISTRATIVE_LAWYER("Administrative Lawyer", "Administrative Lawyer"),
    ENVIRONMENTAL_ATTORNEY("Environmental Attorney", "Environmental Attorney"),
    REAL_ESTATE_ATTORNEY("Real Estate Attorney", "Real Estate Attorney"),
    BANKRUPTCY_ATTORNEY("Bankruptcy Attorney", "Bankruptcy Attorney"),
    LABOR_ATTORNEY("Labor Attorney", "Labor Attorney"),
    SECURITIES_ATTORNEY("Securities Attorney", "Securities Attorney"),
    MEDICAL_MALPRACTICE_ATTORNEY("Medical Malpractice Attorney", "Medical Malpractice Attorney"),
    WORKERS_COMPENSATION_ATTORNEY("Workers Compensation Attorney", "Workers Compensation Attorney"),
    CRIMINAL_PROSECUTOR("Criminal Prosecutor", "Criminal Prosecutor"),
    LITIGATOR("Litigator", "Litigator"),
    CONTRACTS_MANAGER("Contracts Manager", "Contracts Manager"),
    REGULATORY_AFFAIRS_MANAGER("Regulatory Affairs Mgr", "Regulatory Affairs Manager"),
    QUALITY_ASSURANCE_MANAGER("QA Manager", "Quality Assurance Manager"),
    SAFETY_OFFICER("Safety Officer", "Safety Officer"),
    CORPORATE_COMPLIANCE_OFFICER("Corporate Compliance Officer", "Corporate Compliance Officer"),
    BANKER("Banker", "Banker"),
    TAX_PREPARER("Tax Preparer", "Tax Preparer"),
    LOAN_OFFICER("Loan Officer", "Loan Officer"),
    MORTGAGE_BROKER("Mortgage Broker", "Mortgage Broker"),
    ACTUARY("Actuary", "Actuary"),
    ACTUARIAL_ANALYST("Actuarial Analyst", "Actuarial Analyst"),
    UNDERWRITER("Underwriter", "Underwriter"),
    FINANCIAL_EXAMINER("Financial Examiner", "Financial Examiner"),
    CREDIT_ANALYST("Credit Analyst", "Credit Analyst"),
    INVESTMENT_BANKER("Investment Banker", "Investment Banker"),
    EQUITY_ANALYST("Equity Analyst", "Equity Analyst"),
    FIXED_INCOME_ANALYST("Fixed Income Analyst", "Fixed Income Analyst"),
    MERCHANT_BANKER("Merchant Banker", "Merchant Banker"),
    PORTFOLIO_MANAGER("Portfolio Manager", "Portfolio Manager"),
    PRIVATE_EQUITY_ANALYST("Private Equity Analyst", "Private Equity Analyst"),
    VENTURE_CAPITAL_ANALYST("Venture Capital Analyst", "Venture Capital Analyst"),
    SALES_ENGINEER("Sales Engineer", "Sales Engineer"),
    SALES_EXECUTIVE("Sales Executive", "Sales Executive"),
    SALES_MANAGER("Sales Manager", "Sales Manager"),
    BUSINESS_DEVELOPMENT_MANAGER("Biz Dev Mgr", "Business Development Manager"),
    CUSTOMER_SERVICE_MANAGER("Customer Service Manager", "Customer Service Manager"),
    DIRECTOR_OF_OPERATIONS("Director of Ops", "Director of Operations"),
    CHIEF_EXECUTIVE_OFFICER("CEO", "Chief Executive Officer"),
    CHIEF_HUMAN_RESOURCES_OFFICER("CHRO", "Chief Human Resources Officer"),
    CHIEF_COMPLIANCE_OFFICER("CCO", "Chief Compliance Officer"),
    CHIEF_DATA_OFFICER("CDO", "Chief Data Officer"),
    CHIEF_INFORMATION_OFFICER("CIO", "Chief Information Officer"),
    CHIEF_STRATEGY_OFFICER("CSO", "Chief Strategy Officer"),
    VICE_PRESIDENT_OF_FINANCE("VP Finance", "Vice President of Finance"),
    VICE_PRESIDENT_OF_MARKETING("VP Marketing", "Vice President of Marketing"),
    VICE_PRESIDENT_OF_ENGINEERING("VP Engineering", "Vice President of Engineering"),
    VICE_PRESIDENT_OF_OPERATIONS("VP Ops", "Vice President of Operations"),
    VICE_PRESIDENT_OF_PRODUCT("VP Product", "Vice President of Product"),
    VICE_PRESIDENT_OF_TECHNOLOGY("VP Technology", "Vice President of Technology"),
    VICE_PRESIDENT_OF_COMPLIANCE("VP Compliance", "Vice President of Compliance"),
    VICE_PRESIDENT_OF_DATA("VP Data", "Vice President of Data"),
    VICE_PRESIDENT_OF_INFORMATION("VP Info", "Vice President of Information"),
    VICE_PRESIDENT_OF_STRATEGY("VP Strategy", "Vice President of Strategy"),
    VICE_PRESIDENT_OF_COMMUNICATIONS("VP Comm", "Vice President of Communications"),
    VICE_PRESIDENT_OF_RESEARCH("VP Research", "Vice President of Research"),
    VICE_PRESIDENT_OF_DEVOPS("VP DevOps", "Vice President of DevOps"),
    DIRECTOR_OF_RESEARCH("Director of Research", "Director of Research"),
    DIRECTOR_OF_STRATEGY("Director of Strategy", "Director of Strategy"),
    DIRECTOR_OF_PRODUCT("Director of Product", "Director of Product"),
    DIRECTOR_OF_ENGINEERING("Director of Engineering", "Director of Engineering"),
    DIRECTOR_OF_FINANCE("Director of Finance", "Director of Finance"),
    DIRECTOR_OF_COMPLIANCE("Director of Compliance", "Director of Compliance"),
    DIRECTOR_OF_HUMAN_RESOURCES("Director of HR", "Director of Human Resources"),
    DIRECTOR_OF_INFORMATION("Director of Information", "Director of Information"),
    DIRECTOR_OF_DATA("Director of Data", "Director of Data"),
    DIRECTOR_OF_COMMUNICATIONS("Director of Communications", "Director of Communications"),
    DIRECTOR_OF_USER_EXPERIENCE("Director of UX", "Director of User Experience"),
    DIRECTOR_OF_SALES("Director of Sales", "Director of Sales"),
    DIRECTOR_OF_CUSTOMER_SERVICE("Director of Customer Service", "Director of Customer Service"),
    DIRECTOR_OF_MARKETING("Director of Marketing", "Director of Marketing"),
    DIRECTOR_OF_BUSINESS_DEVELOPMENT("Director of Biz Dev", "Director of Business Development"),
    DIRECTOR_OF_PROJECT_MANAGEMENT("Director of Project Management", "Director of Project Management"),
    MANAGER_OF_FINANCE("Finance Manager", "Manager of Finance"),
    ;

    private final String abbreviation;
    private final String value;

    Salutation(final String abbreviation, final String value) {
        this.abbreviation = abbreviation;
        this.value = value;
    }

    public String getabbreviation() {
        return this.abbreviation;
    }

    public String getvalue() {
        return this.value;
    }
}
