package com.github.justincranford.springs.persistenceorm.users.person.enums;

@SuppressWarnings({"nls", "hiding"})
public enum SalutationType {
    DR("Doctor"),
    MR("Mister"),
    MRS("Missus"),
    MS("Miss"),
    MX("Gender-neutral"),
    PROF("Professor"),
    SIR("Sir"),
    MADAM("Madam"),
    REV("Reverend"),
    CAPT("Captain"),
    MAJ("Major"),
    COL("Colonel"),
    LT("Lieutenant"),
    SGT("Sergeant"),
    DRMRS("Doctor Missus"),
    DRMS("Doctor Miss"),
    HON("Honorable"),
    SEN("Senator"),
    JUDGE("Judge"),
    AMB("Ambassador"),
    DAME("Dame"),
    BARON("Baron"),
    BARONESS("Baroness"),
    LORD("Lord"),
    LADY("Lady"),
    COUNT("Count"),
    COUNTESS("Countess"),
    GENERAL("General"),
    CAPTAIN("Captain"),
    COMMANDER("Commander"),
    MAJORGENERAL("Major General"),
    ADMIRAL("Admiral"),
    CHIEF("Chief"),
    HEAD("Head"),
    MENTOR("Mentor"),
    PASTOR("Pastor"),
    FATHER("Father"),
    MOTHER("Mother"),
    SHEIKH("Sheikh"),
    ELDER("Elder"),
    SULTAN("Sultan"),
    RAJA("Raja"),
    RANI("Rani"),
    HEADMASTER("Headmaster"),
    COACH("Coach"),
    CANDIDATE("Candidate"),
    VIP("Very Important Person"),
    EXECUTIVE("Executive"),
    DIRECTOR("Director"),
    CEO("Chief Executive Officer"),
    PRESIDENT("President"),
    VICEPRESIDENT("Vice President"),
    OFFICER("Officer"),
    SPECIALIST("Specialist"),
    ANALYST("Analyst"),
    DIRECTORGENERAL("Director General"),
    EMERITUS("Emeritus"),
    PROFESSOREMERITUS("Professor Emeritus"),
    DOCTOROFMEDICINE("Doctor of Medicine"),
    DOCTOROFPHILOSOPHY("Doctor of Philosophy"),
    DOCTOROFLAW("Juris Doctor"),
    TEACHER("Teacher"),
    NURSE("Nurse"),
    COUNSELOR("Counselor"),
    THERAPIST("Therapist"),
    BISHOP("Bishop"),
    CARDINAL("Cardinal"),
    ARCHBISHOP("Archbishop"),
    MINISTER("Minister"),
    REVERENDFATHER("Reverend Father"),
    REVERENDMOTHER("Reverend Mother"),
    FATHERSUPERIOR("Father Superior"),
    MASTER("Master"),
    LADYSUPERIOR("Lady Superior"),
    VASSAL("Vassal"),
    EXECUTIVEDIRECTOR("Executive Director"),
    OPERATIONSMANAGER("Operations Manager"),
    PROJECTMANAGER("Project Manager"),
    PRODUCTMANAGER("Product Manager"),
    ACCOUNTMANAGER("Account Manager"),
    TEAMLEADER("Team Leader"),
    ASSISTANT("Assistant"),
    SPECIALADVISOR("Special Advisor"),
    HONORABLEJUDGE("Honorable Judge"),
    AMBASSADOREXTRAORDINARY("Ambassador Extraordinary"),
    HIGHCOMMISSIONER("High Commissioner"),
    LEGATE("Legate"),
    PROCONSUL("Proconsul"),
    PREFECT("Prefect"),
    ATTACHE("Attaché"),
    CONSUL("Consul"),
    SUBDIRECTOR("Subdirector"),
    FIRSTLIEUTENANT("First Lieutenant"),
    SECONDLIEUTENANT("Second Lieutenant"),
    LIEUTENANTGENERAL("Lieutenant General"),
    AIRMARSHAL("Air Marshal"),
    COMMANDANT("Commandant"),
    BRIGADIER("Brigadier"),
    FLIGHTLIEUTENANT("Flight Lieutenant"),
    CAPTAINGENERAL("Captain General"),
    SQUADRONLEADER("Squadron Leader"),
    CHIEFEXECUTIVE("Chief Executive"),
    MANAGINGDIRECTOR("Managing Director"),
    VICECHANCELLOR("Vice Chancellor"),
    DEAN("Dean"),
    HEADOFDEPARTMENT("Head of Department"),
    LABMANAGER("Laboratory Manager"),
    RESEARCHDIRECTOR("Research Director"),
    TRAININGDIRECTOR("Training Director"),
    PROGRAMMANAGER("Program Manager"),
    OPERATIONSEXECUTIVE("Operations Executive"),
    BUSINESSANALYST("Business Analyst"),
    MARKETINGMANAGER("Marketing Manager"),
    SALESDIRECTOR("Sales Director"),
    CHIEFMARKETINGOFFICER("Chief Marketing Officer"),
    CHIEFFINANCIALOFFICER("Chief Financial Officer"),
    CHIEFOPERATINGOFFICER("Chief Operating Officer"),
    VICEPRESIDENTOFSALES("Vice President of Sales"),
    CHIEFTECHNOLOGYOFFICER("Chief Technology Officer"),
    SOFTWAREENGINEER("Software Engineer"),
    NETWORKENGINEER("Network Engineer"),
    SYSTEMSANALYST("Systems Analyst"),
    WEBDEVELOPER("Web Developer"),
    DATABASEADMINISTRATOR("Database Administrator"),
    PROJECTCOORDINATOR("Project Coordinator"),
    TECHNICALSUPPORT("Technical Support"),
    CUSTOMERSERVICEREP("Customer Service Representative"),
    HUMANRESOURCESMANAGER("Human Resources Manager"),
    TRAINER("Trainer"),
    EVENTCOORDINATOR("Event Coordinator"),
    CONFERENCEMANAGER("Conference Manager"),
    RECRUITER("Recruiter"),
    TALENTACQUISITIONMANAGER("Talent Acquisition Manager"),
    LEGALADVISOR("Legal Advisor"),
    CORPORATELAWYER("Corporate Lawyer"),
    LITIGATIONATTORNEY("Litigation Attorney"),
    CRIMINALDEFENSEATTORNEY("Criminal Defense Attorney"),
    FAMILYLAWYER("Family Lawyer"),
    TAXATTORNEY("Tax Attorney"),
    PATENTATTORNEY("Patent Attorney"),
    IMMIGRATIONATTORNEY("Immigration Attorney"),
    PARALEGAL("Paralegal"),
    LEGALSECRETARY("Legal Secretary"),
    ACCOUNTANT("Accountant"),
    FINANCIALANALYST("Financial Analyst"),
    AUDITOR("Auditor"),
    CONTROLLER("Controller"),
    TREASURER("Treasurer"),
    FINANCEMANAGER("Finance Manager"),
    DATASCIENTIST("Data Scientist"),
    DATAANALYST("Data Analyst"),
    STATISTICIAN("Statistician"),
    RESEARCHANALYST("Research Analyst"),
    OPERATIONSANALYST("Operations Analyst"),
    MARKETRESEARCHANALYST("Market Research Analyst"),
    JOURNALIST("Journalist"),
    EDITOR("Editor"),
    COLUMNIST("Columnist"),
    REPORTER("Reporter"),
    NEWSANCHOR("News Anchor"),
    BROADCASTJOURNALIST("Broadcast Journalist"),
    PUBLICRELATIONSSPECIALIST("Public Relations Specialist"),
    CONTENTWRITER("Content Writer"),
    COPYWRITER("Copywriter"),
    SOCIALMEDIAMANAGER("Social Media Manager"),
    GRAPHICDESIGNER("Graphic Designer"),
    ARTDIRECTOR("Art Director"),
    PHOTOGRAPHER("Photographer"),
    VIDEOEDITOR("Video Editor"),
    CREATIVEDIRECTOR("Creative Director"),
    MARKETINGANALYST("Marketing Analyst"),
    PRODUCTDESIGNER("Product Designer"),
    UIUXDESIGNER("UI/UX Designer"),
    HRBUSINESSPARTNER("HR Business Partner"),
    OFFICEMANAGER("Office Manager"),
    FACILITYMANAGER("Facility Manager"),
    RECEPTIONIST("Receptionist"),
    EXECUTIVEASSISTANT("Executive Assistant"),
    PERSONALASSISTANT("Personal Assistant"),
    OFFICECOORDINATOR("Office Coordinator"),
    OFFICECLEANER("Office Cleaner"),
    SECURITYGUARD("Security Guard"),
    MAINTENANCEWORKER("Maintenance Worker"),
    CATERER("Caterer"),
    CHEF("Chef"),
    COOK("Cook"),
    SERVER("Server"),
    BARISTA("Barista"),
    WAITER("Waiter"),
    BARTENDER("Bartender"),
    FRONTDESKMANAGER("Front Desk Manager"),
    FRONTDESKCLERK("Front Desk Clerk"),
    TRAVELAGENT("Travel Agent"),
    FLIGHTATTENDANT("Flight Attendant"),
    AIRLINEPILOT("Airline Pilot"),
    CONDUCTOR("Conductor"),
    BUSDRIVER("Bus Driver"),
    RAILWAYSTATIONMANAGER("Railway Station Manager"),
    SCHOOLPRINCIPAL("School Principal"),
    ASSISTANTPRINCIPAL("Assistant Principal"),
    SCHOOLCOUNSELOR("School Counselor"),
    COORDINATOR("Coordinator"),
    STUDENT("Student"),
    ALUMNUS("Alumnus"),
    POSTGRADUATE("Postgraduate"),
    UNDERGRADUATE("Undergraduate"),
    GUESTLECTURER("Guest Lecturer"),
    INTERNSHIPSUPERVISOR("Internship Supervisor"),
    GUESTSPEAKER("Guest Speaker"),
    FACULTYADVISOR("Faculty Advisor"),
    ASSISTANTINSTRUCTOR("Assistant Instructor"),
    LABTECHNICIAN("Laboratory Technician"),
    RESEARCHFELLOW("Research Fellow"),
    GRADUATESTUDENT("Graduate Student"),
    UNDERGRADUATESTUDENT("Undergraduate Student"),
    DOCTORALSTUDENT("Doctoral Student"),
    POSTDOC("Postdoctoral Fellow"),
    THESISSUPERVISOR("Thesis Supervisor"),
    RESEARCHASSOCIATE("Research Associate"),
    FIELDRESEARCHER("Field Researcher"),
    DATACOLLECTIONMANAGER("Data Collection Manager"),
    STATISTICALANALYST("Statistical Analyst"),
    QUANTITATIVEANALYST("Quantitative Analyst"),
    QUALITATIVEANALYST("Qualitative Analyst"),
    COMPLIANCEOFFICER("Compliance Officer"),
    RISKMANAGER("Risk Manager"),
    AUDITMANAGER("Audit Manager"),
    INSURANCEAGENT("Insurance Agent"),
    CLAIMSADJUSTER("Claims Adjuster"),
    FINANCIALADVISOR("Financial Advisor"),
    INVESTMENTANALYST("Investment Analyst"),
    STOCKBROKER("Stock Broker"),
    TRADINGANALYST("Trading Analyst"),
    RISKANALYST("Risk Analyst"),
    COMMODITIESTRADER("Commodities Trader"),
    FISCALANALYST("Fiscal Analyst"),
    ENERGYANALYST("Energy Analyst"),
    SOCIALWORKER("Social Worker"),
    COMMUNITYORGANIZER("Community Organizer"),
    NONPROFITMANAGER("Nonprofit Manager"),
    CHARITYWORKER("Charity Worker"),
    VOLUNTEERCOORDINATOR("Volunteer Coordinator"),
    GRANTWRITER("Grant Writer"),
    FUNDRAISER("Fundraiser"),
    ADVOCATE("Advocate"),
    STRATEGIST("Strategist"),
    COUNCILMEMBER("Council Member"),
    MAYOR("Mayor"),
    CITYMANAGER("City Manager"),
    COUNTYEXECUTIVE("County Executive"),
    GOVERNOR("Governor"),
    STATELEGISLATOR("State Legislator"),
    CONGRESSPERSON("Congressperson"),
    SENATOR("Senator"),
    REPRESENTATIVE("Representative"),
    FEDERALOFFICIAL("Federal Official"),
    AMBASSADOR("Ambassador"),
    MINISTEROFFINANCE("Minister of Finance"),
    SECRETARYOFSTATE("Secretary of State"),
    PRESIDENTOFCOUNTRY("President of Country"),
    PRIMEMINISTER("Prime Minister"),
    CHANCELLOR("Chancellor"),
    CABINETMEMBER("Cabinet Member"),
    TRADEREPRESENTATIVE("Trade Representative"),
    AMBASSADORPLENIPOTENTIARY("Ambassador Plenipotentiary"),
    AMBASSADORATLARGE("Ambassador at Large"),
    SPECIALENVOY("Special Envoy"),
    INTERNATIONALDELEGATE("International Delegate"),
    FOREIGNAFFAIRSSPECIALIST("Foreign Affairs Specialist"),
    ECONOMICADVISOR("Economic Advisor"),
    SECURITYADVISOR("Security Advisor"),
    TECHNICALADVISOR("Technical Advisor"),
    MEDICALADVISOR("Medical Advisor"),
    SCIENCEADVISOR("Science Advisor"),
    CULTURALADVISOR("Cultural Advisor"),
    ENVIRONMENTALADVISOR("Environmental Advisor"),
    PUBLICPOLICYADVISOR("Public Policy Advisor"),
    STRATEGICPLANNER("Strategic Planner"),
    POLICYANALYST("Policy Analyst"),
    COMMUNITYDEVELOPER("Community Developer"),
    URBANPLANNER("Urban Planner"),
    ARCHITECT("Architect"),
    LANDSCAPEARCHITECT("Landscape Architect"),
    INTERIORDESIGNER("Interior Designer"),
    CIVILENGINEER("Civil Engineer"),
    MECHANICALENGINEER("Mechanical Engineer"),
    ELECTRICALENGINEER("Electrical Engineer"),
    SOFTWAREDEVELOPER("Software Developer"),
    HARDWAREENGINEER("Hardware Engineer"),
    SYSTEMSENGINEER("Systems Engineer"),
    TESTENGINEER("Test Engineer"),
    APPLICATIONDEVELOPER("Application Developer"),
    WEBDESIGNER("Web Designer"),
    DATAENGINEER("Data Engineer"),
    NETWORKADMINISTRATOR("Network Administrator"),
    SYSTEMADMINISTRATOR("System Administrator"),
    ITSUPPORTSPECIALIST("IT Support Specialist"),
    DATABASEDEVELOPER("Database Developer"),
    BUSINESSINTELLIGENCEANALYST("Business Intelligence Analyst"),
    ITPROJECTMANAGER("IT Project Manager"),
    ECOMMERCEMANAGER("E-commerce Manager"),
    SOCIALMEDIASPECIALIST("Social Media Specialist"),
    DIGITALMARKETINGMANAGER("Digital Marketing Manager"),
    CONTENTMARKETINGMANAGER("Content Marketing Manager"),
    SEOSPECIALIST("SEO Specialist"),
    PPCSPECIALIST("PPC Specialist"),
    EMAILMARKETINGMANAGER("Email Marketing Manager"),
    AFFILIATEMARKETINGMANAGER("Affiliate Marketing Manager"),
    COMMUNITYMANAGER("Community Manager"),
    ANALYTICSMANAGER("Analytics Manager"),
    USEREXPERIENCERESEARCHER("User Experience Researcher"),
    USERINTERFACEDEVELOPER("User Interface Developer"),
    VIRTUALASSISTANT("Virtual Assistant"),
    PROJECTASSISTANT("Project Assistant"),
    SALESASSOCIATE("Sales Associate"),
    STOREMANAGER("Store Manager"),
    DISTRICTMANAGER("District Manager"),
    REGIONALMANAGER("Regional Manager"),
    VICEPRESIDENTOFHUMANRESOURCES("Vice President of Human Resources"),
    PROCUREMENTMANAGER("Procurement Manager"),
    SUPPLYCHAINMANAGER("Supply Chain Manager"),
    LOGISTICSMANAGER("Logistics Manager"),
    CUSTOMERSUCCESSMANAGER("Customer Success Manager"),
    CLIENTSERVICESMANAGER("Client Services Manager"),
    PRODUCTQUALITYMANAGER("Product Quality Manager"),
    HEALTHCAREMANAGER("Healthcare Manager"),
    HEALTHCAREADMINISTRATOR("Healthcare Administrator"),
    CLINICALDIRECTOR("Clinical Director"),
    MEDICALDIRECTOR("Medical Director"),
    PHYSICIANASSISTANT("Physician Assistant"),
    PHARMACIST("Pharmacist"),
    NURSEPRACTITIONER("Nurse Practitioner"),
    REGISTEREDNURSE("Registered Nurse"),
    LICENSEDPRACTICALNURSE("Licensed Practical Nurse"),
    CERTIFIEDNURSINGASSISTANT("Certified Nursing Assistant"),
    MEDICALTECHNICIAN("Medical Technician"),
    RESPIRATORYTHERAPIST("Respiratory Therapist"),
    RADIOLOGICTECHNOLOGIST("Radiologic Technologist"),
    DENTIST("Dentist"),
    ORTHODONTIST("Orthodontist"),
    VETERINARIAN("Veterinarian"),
    ANIMALTECHNICIAN("Animal Technician"),
    DENTALHYGIENIST("Dental Hygienist"),
    PHYSICALTHERAPIST("Physical Therapist"),
    OCCUPATIONALTHERAPIST("Occupational Therapist"),
    SPEECHLANGUAGEPATHOLOGIST("Speech Language Pathologist"),
    SOCIALSERVICESMANAGER("Social Services Manager"),
    PSYCHOLOGIST("Psychologist"),
    CLINICALSOCIALWORKER("Clinical Social Worker"),
    BEHAVIORANALYST("Behavior Analyst"),
    MENTALHEALTHCOUNSELOR("Mental Health Counselor"),
    SCHOOLSOCIALWORKER("School Social Worker"),
    SCHOOLPSYCHOLOGIST("School Psychologist"),
    REHABILITATIONCOUNSELOR("Rehabilitation Counselor"),
    PARENTINGCOORDINATOR("Parenting Coordinator"),
    ALTERNATIVEDISPUTERESOLUTIONSPECIALIST("Alternative Dispute Resolution Specialist"),
    SOCIALSERVICESCOORDINATOR("Social Services Coordinator"),
    CLINICALMANAGER("Clinical Manager"),
    SYSTEMSTHINKER("Systems Thinker"),
    STRATEGICTHINKER("Strategic Thinker"),
    CREATIVETHINKER("Creative Thinker"),
    CRITICALTHINKER("Critical Thinker"),
    PROBLEMSOLVER("Problem Solver"),
    DECISIONMAKER("Decision Maker"),
    INNOVATOR("Innovator"),
    CHANGEAGENT("Change Agent"),
    TEAMBUILDER("Team Builder"),
    RELATIONSHIPBUILDER("Relationship Builder"),
    NETWORKINGSPECIALIST("Networking Specialist"),
    PROFESSIONALDEVELOPER("Professional Developer"),
    EXECUTIVECOACH("Executive Coach"),
    LEADERSHIPDEVELOPER("Leadership Developer"),
    SUCCESSCOACH("Success Coach"),
    BUSINESSMENTOR("Business Mentor"),
    CAREERCOACH("Career Coach"),
    COMMUNICATIONSCOACH("Communications Coach"),
    FINANCIALCOACH("Financial Coach"),
    HEALTHCOACH("Health Coach"),
    LIFECOACH("Life Coach"),
    YOGAINSTRUCTOR("Yoga Instructor"),
    PERSONALTRAINER("Personal Trainer"),
    FITNESSINSTRUCTOR("Fitness Instructor"),
    WELLNESSCOACH("Wellness Coach"),
    SPIRITUALGUIDE("Spiritual Guide"),
    MEDITATIONTEACHER("Meditation Teacher"),
    MINDFULNESSINSTRUCTOR("Mindfulness Instructor"),
    COUNSELOROFLIFE("Counselor of Life"),
    LIFESCHOOL("Life School"),
    LIFEEXPERT("Life Expert"),
    COMMUNITYHEALTHWORKER("Community Health Worker"),
    HEALTHPROMOTER("Health Promoter"),
    PEERSUPPORTWORKER("Peer Support Worker"),
    SOCIALWORKERSUPERVISOR("Social Worker Supervisor"),
    YOUTHWORKER("Youth Worker"),
    AGINGSERVICESWORKER("Aging Services Worker"),
    DISABILITYSERVICESWORKER("Disability Services Worker"),
    HOMEHEALTHAIDE("Home Health Aide"),
    HOSPICEWORKER("Hospice Worker"),
    ADOPTIONWORKER("Adoption Worker"),
    CANCERSUPPORTWORKER("Cancer Support Worker"),
    SUBSTANCEABUSECOUNSELOR("Substance Abuse Counselor"),
    MENTALHEALTHWORKER("Mental Health Worker"),
    DOMESTICVIOLENCEADVOCATE("Domestic Violence Advocate"),
    SEXUALASSAULTADVOCATE("Sexual Assault Advocate"),
    VICTIMADVOCATE("Victim Advocate"),
    TRAUMAINFORMEDSPECIALIST("Trauma Informed Specialist"),
    NEIGHBORHOODCOORDINATOR("Neighborhood Coordinator"),
    NONPROFITVOLUNTEER("Nonprofit Volunteer"),
    SOCIALCHANGEAGENT("Social Change Agent"),
    GRASSROOTSACTIVIST("Grassroots Activist"),
    PUBLICINTERESTADVOCATE("Public Interest Advocate"),
    HUMANRIGHTSADVOCATE("Human Rights Advocate"),
    ENVIRONMENTALADVOCATE("Environmental Advocate"),
    EDUCATIONADVOCATE("Education Advocate"),
    VOTERREGISTRATIONSPECIALIST("Voter Registration Specialist"),
    CITIZENACTIONLEADER("Citizen Action Leader"),
    CIVILRIGHTSLEADER("Civil Rights Leader"),
    ANTIPOVERTYACTIVIST("Anti-Poverty Activist"),
    LABORUNIONLEADER("Labor Union Leader"),
    INTERNATIONALAFFAIRSSPECIALIST("International Affairs Specialist"),
    GLOBALHEALTHSPECIALIST("Global Health Specialist"),
    PUBLICHEALTHSPECIALIST("Public Health Specialist"),
    HUMANRESOURCESSPECIALIST("Human Resources Specialist"),
    EMPLOYEERELATIONSSPECIALIST("Employee Relations Specialist"),
    COMPENSATIONANALYST("Compensation Analyst"),
    BENEFITSSPECIALIST("Benefits Specialist"),
    TALENTMANAGEMENTSPECIALIST("Talent Management Specialist"),
    WORKFORCEPLANNINGANALYST("Workforce Planning Analyst"),
    TRAININGANDDEVELOPMENTMANAGER("Training and Development Manager"),
    LEARNINGANDDEVELOPMENTMANAGER("Learning and Development Manager"),
    ORGANIZATIONALDEVELOPMENTSPECIALIST("Organizational Development Specialist"),
    CHANGEMANAGEMENTSPECIALIST("Change Management Specialist"),
    DIVERSITYANDINCLUSIONMANAGER("Diversity and Inclusion Manager"),
    EMPLOYEEENGAGEMENTSPECIALIST("Employee Engagement Specialist"),
    EMPLOYEEWELLNESSCOORDINATOR("Employee Wellness Coordinator"),
    WORKPLACESAFETYSPECIALIST("Workplace Safety Specialist"),
    CULTUREMANAGER("Culture Manager"),
    ENVIRONMENTALSCIENTIST("Environmental Scientist"),
    GEOLOGIST("Geologist"),
    OCEANOGRAPHER("Oceanographer"),
    METEOROLOGIST("Meteorologist"),
    CLIMATOLOGIST("Climatologist"),
    ATMOSPHERICSCIENTIST("Atmospheric Scientist"),
    ECOLOGIST("Ecologist"),
    CONSERVATIONBIOLOGIST("Conservation Biologist"),
    WILDLIFEBIOLOGIST("Wildlife Biologist"),
    ZOOLOGIST("Zoologist"),
    MARINEBIOLOGIST("Marine Biologist"),
    BIOLOGIST("Biologist"),
    BIOCHEMIST("Biochemist"),
    MOLECULARBIOLOGIST("Molecular Biologist"),
    GENETICIST("Geneticist"),
    PHYSICIST("Physicist"),
    CHEMIST("Chemist"),
    ANTHROPOLOGIST("Anthropologist"),
    SOCIOLOGIST("Sociologist"),
    ARCHAEOLOGIST("Archaeologist"),
    HISTORIAN("Historian"),
    PHILOSOPHER("Philosopher"),
    CULTURALANTHROPOLOGIST("Cultural Anthropologist"),
    ECONOMIST("Economist"),
    POLITICALSCIENTIST("Political Scientist"),
    ETHICIST("Ethicist"),
    CLASSICALSCHOLAR("Classical Scholar"),
    LITERARYCRITIC("Literary Critic"),
    ARTCRITIC("Art Critic"),
    THEATERCRITIC("Theater Critic"),
    FILMCRITIC("Film Critic"),
    MUSICOLOGIST("Musicologist"),
    THEOLOGIAN("Theologian"),
    ARCHITECTURALHISTORIAN("Architectural Historian"),
    FOODCRITIC("Food Critic"),
    PERFORMANCEARTCRITIC("Performance Art Critic"),
    DANCECRITIC("Dance Critic"),
    LITERARYAGENT("Literary Agent"),
    BOOKEDITOR("Book Editor"),
    MOVIEPRODUCER("Movie Producer"),
    TELEVISIONPRODUCER("Television Producer"),
    RADIOPRODUCER("Radio Producer"),
    DOCUMENTARYFILMMAKER("Documentary Filmmaker"),
    SCREENWRITER("Screenwriter"),
    NOVELIST("Novelist"),
    POET("Poet"),
    PLAYWRIGHT("Playwright"),
    ARTIST("Artist"),
    PHOTOGRAPHICARTIST("Photographic Artist"),
    GRAPHICNOVELIST("Graphic Novelist"),
    SCULPTOR("Sculptor"),
    MUSICIAN("Musician"),
    SONGWRITER("Songwriter"),
    DANCER("Dancer"),
    PERFORMER("Performer"),
    COMPOSER("Composer"),
    ARTCOLLECTOR("Art Collector"),
    MUSEUMCURATOR("Museum Curator"),
    EXHIBITIONDESIGNER("Exhibition Designer"),
    GALLERYOWNER("Gallery Owner"),
    ARCHITECTURALDESIGNER("Architectural Designer"),
    INTERIORDECORATOR("Interior Decorator"),
    CRAFTARTIST("Craft Artist"),
    THEATERDIRECTOR("Theater Director"),
    FILMDIRECTOR("Film Director"),
    MUSICDIRECTOR("Music Director"),
    DANCEDIRECTOR("Dance Director"),
    ARTTEACHER("Art Teacher"),
    MUSICTEACHER("Music Teacher"),
    DRAMATEACHER("Drama Teacher"),
    DANCETEACHER("Dance Teacher"),
    ARTTUTOR("Art Tutor"),
    MUSICTUTOR("Music Tutor"),
    DRAMATUTOR("Drama Tutor"),
    DANCETUTOR("Dance Tutor"),
    ARTHISTORIAN("Art Historian"),
    MUSICHISTORIAN("Music Historian"),
    DANCEHISTORIAN("Dance Historian"),
    THEATERHISTORIAN("Theater Historian"),
    CRITIC("Critic"),
    ACADEMIC("Academic"),
    CURATOR("Curator"),
    PROGRAMDIRECTOR("Program Director"),
    INITIATIVECOORDINATOR("Initiative Coordinator"),
    CONFERENCER("Conferencer"),
    WEBINARHOST("Webinar Host"),
    WEBCASTER("Webcaster"),
    BROADCASTER("Broadcaster"),
    DOCUMENTARYNARRATOR("Documentary Narrator"),
    VOICEOVERARTIST("Voice Over Artist"),
    AUDIOENGINEER("Audio Engineer"),
    SOUNDDESIGNER("Sound Designer"),
    MUSICPRODUCER("Music Producer"),
    ORCHESTRATOR("Orchestrator"),
    MUSICTECHNOLOGIST("Music Technologist"),
    TECHNICALDIRECTOR("Technical Director"),
    PROGRAMMER("Programmer"),
    COMPUTERSCIENTIST("Computer Scientist"),
    ARTIFICIALINTELLIGENCEENGINEER("Artificial Intelligence Engineer"),
    INFORMATIONARCHITECT("Information Architect"),
    SYSTEMARCHITECT("System Architect"),
    CLOUDARCHITECT("Cloud Architect"),
    DEVOPSENGINEER("DevOps Engineer"),
    CYBERSECURITYSPECIALIST("Cybersecurity Specialist"),
    BLOCKCHAINDEVELOPER("Blockchain Developer"),
    TECHSUPPORTENGINEER("Tech Support Engineer"),
    RESEARCHDEVELOPER("Research Developer"),
    FIELDSERVICEENGINEER("Field Service Engineer"),
    SOFTWAREQUALITYENGINEER("Software Quality Engineer"),
    GAMEDEVELOPER("Game Developer"),
    VIRTUALREALITYDEVELOPER("Virtual Reality Developer"),
    AUGMENTEDREALITYDEVELOPER("Augmented Reality Developer"),
    ROBOTICSENGINEER("Robotics Engineer"),
    GAMEDESIGNER("Game Designer"),
    GAMETESTER("Game Tester"),
    GAMEWRITER("Game Writer"),
    UIDEVELOPER("UI Developer"),
    GAMENARRATIVEDESIGNER("Game Narrative Designer"),
    USERINTERFACEDESIGNER("User Interface Designer"),
    GAMEGRAPHICARTIST("Game Graphic Artist"),
    GAMEMUSICCOMPOSER("Game Music Composer"),
    LEVELDESIGNER("Level Designer"),
    TECHNICALARTIST("Technical Artist"),
    ARTCONCEPTUALIZER("Art Conceptualizer"),
    NARRATIVEDESIGNER("Narrative Designer"),
    ANIMATOR("Animator"),
    VISUALEFFECTSARTIST("Visual Effects Artist"),
    CHARACTERMODELER("Character Modeler"),
    ENVIRONMENTARTIST("Environment Artist"),
    RIGGER("Rigger"),
    LIGHTINGARTIST("Lighting Artist"),
    SCRIPTWRITER("Script Writer"),
    COMPOSITOR("Compositor"),
    MOTIONGRAPHICDESIGNER("Motion Graphic Designer"),
    BRANDSTRATEGIST("Brand Strategist"),
    SOCIALMEDIASTRATEGIST("Social Media Strategist"),
    EMAILMARKETINGSPECIALIST("Email Marketing Specialist"),
    DIGITALMEDIABUYER("Digital Media Buyer"),
    FRONTENDDEVELOPER("Front-End Developer"),
    BACKENDDEVELOPER("Back-End Developer"),
    FULLSTACKDEVELOPER("Full-Stack Developer"),
    MOBILEAPPDEVELOPER("Mobile App Developer"),
    SYSTEMSADMINISTRATOR("Systems Administrator"),
    SECURITYADMINISTRATOR("Security Administrator"),
    TECHNICALWRITER("Technical Writer"),
    CONTENTSTRATEGIST("Content Strategist"),
    INFORMATIONSECURITYANALYST("Information Security Analyst"),
    NETWORKSECURITYSPECIALIST("Network Security Specialist"),
    CLOUDENGINEER("Cloud Engineer"),
    COMPUTERPROGRAMMER("Computer Programmer"),
    PRODUCTDEVELOPER("Product Developer"),
    APPLICATIONSUPPORTANALYST("Application Support Analyst"),
    TECHNICALSUPPORTENGINEER("Technical Support Engineer"),
    SOFTWAREARCHITECT("Software Architect"),
    UXDESIGNER("User Experience Designer"),
    DATAVISUALIZATIONSPECIALIST("Data Visualization Specialist"),
    CUSTOMERINSIGHTSANALYST("Customer Insights Analyst"),
    UXWRITER("User Experience Writer"),
    CONSUMERBEHAVIORANALYST("Consumer Behavior Analyst"),
    DIGITALPRODUCTMANAGER("Digital Product Manager"),
    PUBLICRELATIONSMANAGER("Public Relations Manager"),
    BRANDMANAGER("Brand Manager"),
    SEOMANAGER("SEO Manager"),
    PPCMANAGER("PPC Manager"),
    RADIOLOGICTECHNICIAN("Radiologic Technician"),
    FAMILYTHERAPIST("Family Therapist"),
    CLINICALCARECOORDINATOR("Clinical Care Coordinator"),
    BEHAVIORALHEALTHMANAGER("Behavioral Health Manager"),
    PATIENTNAVIGATOR("Patient Navigator"),
    ADULTDAYCAREWORKER("Adult Day Care Worker"),
    ASSISTEDLIVINGWORKER("Assisted Living Worker"),
    SENIORCAREWORKER("Senior Care Worker"),
    DISABILITYSUPPORTWORKER("Disability Support Worker"),
    CHILDDEVELOPMENTWORKER("Child Development Worker"),
    SCHOOLNURSE("School Nurse"),
    PRIMARYCAREPROVIDER("Primary Care Provider"),
    EMERGENCYMEDICALTECHNICIAN("Emergency Medical Technician"),
    PARAMEDIC("Paramedic"),
    FIREFIGHTER("Firefighter"),
    POLICEOFFICER("Police Officer"),
    CORRECTIONALOFFICER("Correctional Officer"),
    ATTORNEY("Attorney"),
    LEGALAID("Legal Aid"),
    COURTREPORTER("Court Reporter"),
    CORPORATECOUNSEL("Corporate Counsel"),
    FAMILYLAWATTORNEY("Family Law Attorney"),
    PERSONALINJURYATTORNEY("Personal Injury Attorney"),
    ESTATEPLANNINGATTORNEY("Estate Planning Attorney"),
    INTELLECTUALPROPERTYATTORNEY("Intellectual Property Attorney"),
    ADMINISTRATIVELAWYER("Administrative Lawyer"),
    ENVIRONMENTALATTORNEY("Environmental Attorney"),
    REALESTATEATTORNEY("Real Estate Attorney"),
    BANKRUPTCYATTORNEY("Bankruptcy Attorney"),
    LABORATTORNEY("Labor Attorney"),
    SECURITIESATTORNEY("Securities Attorney"),
    MEDICALMALPRACTICEATTORNEY("Medical Malpractice Attorney"),
    WORKERSCOMPENSATIONATTORNEY("Workers Compensation Attorney"),
    CRIMINALPROSECUTOR("Criminal Prosecutor"),
    LITIGATOR("Litigator"),
    CONTRACTSMANAGER("Contracts Manager"),
    REGULATORYAFFAIRSMANAGER("Regulatory Affairs Manager"),
    QUALITYASSURANCEMANAGER("Quality Assurance Manager"),
    SAFETYOFFICER("Safety Officer"),
    CORPORATECOMPLIANCEOFFICER("Corporate Compliance Officer"),
    BANKER("Banker"),
    TAXPREPARER("Tax Preparer"),
    LOANOFFICER("Loan Officer"),
    MORTGAGEBROKER("Mortgage Broker"),
    ACTUARY("Actuary"),
    ACTUARIALANALYST("Actuarial Analyst"),
    UNDERWRITER("Underwriter"),
    FINANCIALEXAMINER("Financial Examiner"),
    CREDITANALYST("Credit Analyst"),
    INVESTMENTBANKER("Investment Banker"),
    EQUITYANALYST("Equity Analyst"),
    FIXEDINCOMEANALYST("Fixed Income Analyst"),
    MERCHANTBANKER("Merchant Banker"),
    PORTFOLIOMANAGER("Portfolio Manager"),
    PRIVATEEQUITYANALYST("Private Equity Analyst"),
    VENTURECAPITALANALYST("Venture Capital Analyst"),
    SALESENGINEER("Sales Engineer"),
    SALESEXECUTIVE("Sales Executive"),
    SALESMANAGER("Sales Manager"),
    BUSINESSDEVELOPMENTMANAGER("Business Development Manager"),
    CUSTOMERSERVICEMANAGER("Customer Service Manager"),
    DIRECTOROFOPERATIONS("Director of Operations"),
    CHIEFEXECUTIVEOFFICER("Chief Executive Officer"),
    CHIEFHUMANRESOURCESOFFICER("Chief Human Resources Officer"),
    CHIEFCOMPLIANCEOFFICER("Chief Compliance Officer"),
    CHIEFDATAOFFICER("Chief Data Officer"),
    CHIEFINFORMATIONOFFICER("Chief Information Officer"),
    CHIEFSTRATEGYOFFICER("Chief Strategy Officer"),
    VICEPRESIDENTOFFINANCE("Vice President of Finance"),
    VICEPRESIDENTOFMARKETING("Vice President of Marketing"),
    VICEPRESIDENTOFENGINEERING("Vice President of Engineering"),
    VICEPRESIDENTOFOPERATIONS("Vice President of Operations"),
    VICEPRESIDENTOFPRODUCT("Vice President of Product"),
    VICEPRESIDENTOFTECHNOLOGY("Vice President of Technology"),
    VICEPRESIDENTOFCOMPLIANCE("Vice President of Compliance"),
    VICEPRESIDENTOFDATA("Vice President of Data"),
    VICEPRESIDENTOFINFORMATION("Vice President of Information"),
    VICEPRESIDENTOFSTRATEGY("Vice President of Strategy"),
    VICEPRESIDENTOFCOMMUNICATIONS("Vice President of Communications"),
    VICEPRESIDENTOFRESEARCH("Vice President of Research"),
    VICEPRESIDENTOFDEVOPS("Vice President of DevOps"),
    DIRECTOROFRESEARCH("Director of Research"),
    DIRECTOROFSTRATEGY("Director of Strategy"),
    DIRECTOROFPRODUCT("Director of Product"),
    DIRECTOROFENGINEERING("Director of Engineering"),
    DIRECTOROFFINANCE("Director of Finance"),
    DIRECTOROFCOMPLIANCE("Director of Compliance"),
    DIRECTOROFHUMANRESOURCES("Director of Human Resources"),
    DIRECTOROFINFORMATION("Director of Information"),
    DIRECTOROFDATA("Director of Data"),
    DIRECTOROFCOMMUNICATIONS("Director of Communications"),
    DIRECTOROFUSEREXPERIENCE("Director of User Experience"),
    DIRECTOROFSALES("Director of Sales"),
    DIRECTOROFCUSTOMERSERVICE("Director of Customer Service"),
    DIRECTOROFMARKETING("Director of Marketing"),
    DIRECTOROFBUSINESSDEVELOPMENT("Director of Business Development"),
    DIRECTOROFPROJECTMANAGEMENT("Director of Project Management"),
    MANAGEROFFINANCE("Manager of Finance"),
    ;

    private final String value;

    SalutationType(final String value) {
        this.value = value;
    }

    public String getvalue() {
        return this.value;
    }
}
